qpid::framing::StructHelper Class Reference
Apache Qpid - AMQP Messaging for Java JMS, C++, Python, Ruby, and .NET Apache Qpid Documentation
qpid::framing::StructHelper Class Reference
#include <qpid/framing/StructHelper.h>
Public Member Functions
template<class T >
void encode (const T &t, std::string &data)
template<class T >
void decode (T &t, const std::string &data)
Member Function Documentation
template<class T > void qpid::framing::StructHelper::decode (T & t, const std::string & data) [inline]
Definition at line 45 of file StructHelper.h.
References qpid::framing::Buffer::getShort().
Referenced by qpid::client::TypedResult::get().
template<class T > void qpid::framing::StructHelper::encode (const T & t, std::string & data) [inline]
Definition at line 37 of file StructHelper.h.
References qpid::framing::Buffer::putShort().
The documentation for this class was generated from the following file:
qpid/framing/StructHelper.h
Qpid C++ API Reference