# Generated makefile fragment.
# Including makefile defines ${rgen_dir} ${rgen_cmd} and ${specs}.

set(rgen_generator ${rgen_dir}/framing.0-10/OperationsInvoker.rb 
    ${rgen_dir}/framing.0-10/MethodBodyConstVisitor.rb 
    ${rgen_dir}/framing.0-10/frame_body_lists.rb 
    ${rgen_dir}/framing.0-10/Proxy.rb 
    ${rgen_dir}/framing.0-10/structs.rb 
    ${rgen_dir}/framing.0-10/constants.rb 
    ${rgen_dir}/framing.0-10/Operations.rb 
    ${rgen_dir}/framing.0-10/all_method_bodies.rb 
    ${rgen_dir}/framing.0-10/MethodBodyFactory.rb 
    ${rgen_dir}/framing.0-10/Session.rb 
    ${rgen_dir}/framing.0-10/MethodBodyDefaultVisitor.rb 
    ${rgen_dir}/amqpgen.rb 
    ${rgen_dir}/0-10/handlers.rb 
    ${rgen_dir}/0-10/typecode.rb 
    ${rgen_dir}/0-10/allsegmenttypes.rb 
    ${rgen_dir}/0-10/exceptions.rb 
    ${rgen_dir}/0-10/specification.rb 
    ${rgen_dir}/cppgen.rb 
    ${rgen_dir}/MethodBodyDefaultVisitor.rb 
    ${rgen_dir}/generate)

set(rgen_client_srcs ../include/qpid/client/AsyncSession_0_10.h 
    ../include/qpid/client/no_keyword/AsyncSession_0_10.h 
    ./qpid/client/no_keyword/AsyncSession_0_10.cpp 
    ../include/qpid/client/no_keyword/Session_0_10.h 
    ../include/qpid/client/Session_0_10.h 
    ../include/qpid/client/arg.h 
    ./qpid/client/no_keyword/Session_0_10.cpp)

set(rgen_framing_srcs ./qpid/framing/MethodBodyDefaultVisitor.cpp 
    ./qpid/framing/FileReturnBody.cpp 
    ../include/qpid/framing/ReplyTo.h 
    ./qpid/framing/DtxRecoverResult.cpp 
    ./qpid/framing/ConnectionCloseBody.cpp 
    ./qpid/framing/FileConsumeOkBody.h 
    ./qpid/framing/TxCommitBody.cpp 
    ./qpid/framing/SessionKnownCompletedBody.h 
    ./qpid/framing/MessageAcquireBody.h 
    ./qpid/framing/DtxSetTimeoutBody.cpp 
    ./qpid/framing/ClusterConnectionConfigBody.cpp 
    ./qpid/framing/ClusterConnectionTxDequeueBody.h 
    ./qpid/framing/ClusterUpdateRequestBody.cpp 
    ./qpid/framing/ExchangeBoundBody.h 
    ../include/qpid/framing/Xid.h 
    ./qpid/framing/SessionGapBody.cpp 
    ./qpid/framing/StreamQosBody.h 
    ./qpid/framing/StreamCancelBody.h 
    ./qpid/framing/ClusterInitialStatusBody.h 
    ./qpid/framing/SessionCompletedBody.h 
    ./qpid/framing/ClusterConnectionDtxWorkRecordBody.h 
    ./qpid/framing/ClusterTimerDropBody.h 
    ./qpid/framing/ConnectionTuneBody.h 
    ./qpid/framing/DtxPrepareBody.cpp 
    ./qpid/framing/ClusterConnectionTxPublishBody.cpp 
    ./qpid/framing/MessageRejectBody.h 
    ./qpid/framing/DeliveryProperties.cpp 
    ./qpid/framing/StreamDeliverBody.h 
    ./qpid/framing/MethodBodyConstVisitor.h 
    ./qpid/framing/ClusterRetractOfferBody.cpp 
    ./qpid/framing/SessionTimeoutBody.h 
    ./qpid/framing/FileRejectBody.h 
    ./qpid/framing/StreamPublishBody.h 
    ./qpid/framing/DtxCommitBody.cpp 
    ./qpid/framing/AMQP_ServerProxy.cpp 
    ./qpid/framing/FilePublishBody.cpp 
    ./qpid/framing/ClusterConnectionAddQueueListenerBody.cpp 
    ./qpid/framing/ClusterConnectionDtxAckBody.h 
    ./qpid/framing/FileStageBody.cpp 
    ./qpid/framing/ClusterConnectionTxEndBody.h 
    ./qpid/framing/ClusterConnectionDtxEndBody.cpp 
    ./qpid/framing/SessionDetachedBody.h 
    ../include/qpid/framing/DtxRecoverResult.h 
    ./qpid/framing/QueueQueryResult.cpp 
    ./qpid/framing/ExchangeQueryBody.cpp 
    ./qpid/framing/SessionAttachBody.h 
    ./qpid/framing/ClusterConnectionShadowSetUserBody.cpp 
    ./qpid/framing/StreamQosOkBody.h 
    ./qpid/framing/FileOpenOkBody.h 
    ./qpid/framing/SessionAttachBody.cpp 
    ./qpid/framing/ClusterConnectionQueueDequeueSincePurgeStateBody.h 
    ../include/qpid/framing/DtxGetTimeoutResult.h 
    ./qpid/framing/FileQosBody.h 
    ./qpid/framing/SessionRequestTimeoutBody.h 
    ./qpid/framing/ClusterConnectionTxDequeueBody.cpp 
    ./qpid/framing/ExchangeUnbindBody.cpp 
    ./qpid/framing/SessionAttachedBody.cpp 
    ./qpid/framing/SessionFlushBody.cpp 
    ./qpid/framing/ClusterConnectionExchangeBody.cpp 
    ./qpid/framing/ExchangeDeleteBody.h 
    ./qpid/framing/FileCancelBody.cpp 
    ./qpid/framing/MessageFlushBody.h 
    ./qpid/framing/ConnectionSecureOkBody.cpp 
    ./qpid/framing/DtxSetTimeoutBody.h 
    ./qpid/framing/FileRejectBody.cpp 
    ../include/qpid/framing/Header.h 
    ../include/qpid/framing/StreamProperties.h 
    ./qpid/framing/AMQP_AllProxy.h 
    ./qpid/framing/ClusterConnectionDtxStartBody.h 
    ./qpid/framing/AllInvoker.cpp 
    ./qpid/framing/FileDeliverBody.h 
    ./qpid/framing/AMQP_ClientOperations.h 
    ./qpid/framing/ClusterConnectionQueuePositionBody.h 
    ./qpid/framing/ClusterConnectionMembershipBody.h 
    ./qpid/framing/ClusterConnectionSessionStateBody.h 
    ./qpid/framing/ClusterConnectionDtxEndBody.h 
    ./qpid/framing/ClusterConnectionDeliverDoOutputBody.cpp 
    ./qpid/framing/ClusterConnectionDeliverCloseBody.h 
    ./qpid/framing/ClusterConnectionAnnounceBody.h 
    ./qpid/framing/ClusterClockBody.h 
    ./qpid/framing/DtxSelectBody.h 
    ./qpid/framing/TxSelectBody.h 
    ../include/qpid/framing/reply_exceptions.h 
    ./qpid/framing/ClusterErrorCheckBody.h 
    ./qpid/framing/SessionConfirmedBody.h 
    ./qpid/framing/MessageFlowBody.cpp 
    ./qpid/framing/StreamQosBody.cpp 
    ./qpid/framing/DtxCommitBody.h 
    ./qpid/framing/ExchangeBoundBody.cpp 
    ./qpid/framing/ExchangeBindBody.h 
    ./qpid/framing/frame_body_lists.h 
    ./qpid/framing/FileConsumeOkBody.cpp 
    ../include/qpid/framing/FragmentProperties.h 
    ./qpid/framing/ClusterUpdateOfferBody.h 
    ./qpid/framing/MessageTransferBody.cpp 
    ./qpid/framing/FileQosOkBody.h 
    ./qpid/framing/ClusterShutdownBody.cpp 
    ./qpid/framing/StreamDeliverBody.cpp 
    ../include/qpid/framing/FileProperties.h 
    ./qpid/framing/ExchangeDeleteBody.cpp 
    ./qpid/framing/ConnectionTuneBody.cpp 
    ./qpid/framing/ExchangeQueryResult.cpp 
    ./qpid/framing/TxCommitBody.h 
    ./qpid/framing/ClientInvoker.h 
    ./qpid/framing/ClusterUpdateOfferBody.cpp 
    ./qpid/framing/reply_exceptions.cpp 
    ./qpid/framing/ClusterConnectionQueueFairshareStateBody.cpp 
    ./qpid/framing/QueueDeclareBody.h 
    ./qpid/framing/StreamConsumeOkBody.h 
    ../include/qpid/framing/constants.h 
    ./qpid/framing/ClusterConnectionManagementSetupStateBody.cpp 
    ./qpid/framing/FilePublishBody.h 
    ./qpid/framing/ConnectionCloseBody.h 
    ./qpid/framing/ConnectionOpenOkBody.cpp 
    ./qpid/framing/ClusterConnectionAbortBody.h 
    ./qpid/framing/ClusterInitialStatusBody.cpp 
    ../include/qpid/framing/XaResult.h 
    ./qpid/framing/XaResult.cpp 
    ./qpid/framing/FileStageBody.h 
    ./qpid/framing/FileAckBody.h 
    ../include/qpid/framing/MessageProperties.h 
    ./qpid/framing/FileQosOkBody.cpp 
    ./qpid/framing/ClusterTimerWakeupBody.cpp 
    ./qpid/framing/ConnectionOpenBody.cpp 
    ./qpid/framing/FileOpenOkBody.cpp 
    ./qpid/framing/StreamConsumeBody.h 
    ./qpid/framing/AMQP_ClientProxy.h 
    ./qpid/framing/QueueDeleteBody.h 
    ./qpid/framing/FileCancelBody.h 
    ./qpid/framing/MessageSubscribeBody.cpp 
    ../include/qpid/framing/enum.h 
    ./qpid/framing/ClusterConnectionQueueFairshareStateBody.h 
    ./qpid/framing/ClusterConnectionDtxBufferRefBody.cpp 
    ./qpid/framing/ClusterConnectionAccumulatedAckBody.cpp 
    ./qpid/framing/MessageAcceptBody.h 
    ./qpid/framing/AMQP_AllProxy.cpp 
    ./qpid/framing/FileConsumeBody.cpp 
    ./qpid/framing/ExecutionExceptionBody.cpp 
    ./qpid/framing/ConnectionCloseOkBody.h 
    ./qpid/framing/ClusterConnectionTxEnqueueBody.cpp 
    ./qpid/framing/ClusterConfigChangeBody.cpp 
    ./qpid/framing/ConnectionStartBody.cpp 
    ./qpid/framing/DtxRecoverBody.h 
    ./qpid/framing/DtxStartBody.h 
    ./qpid/framing/MessageStopBody.h 
    ./qpid/framing/ClientInvoker.cpp 
    ./qpid/framing/MethodBodyFactory.cpp 
    ./qpid/framing/MessageAcceptBody.cpp 
    ../include/qpid/framing/DeliveryProperties.h 
    ./qpid/framing/FileAckBody.cpp 
    ./qpid/framing/QueueQueryBody.cpp 
    ./qpid/framing/ExchangeDeclareBody.h 
    ./qpid/framing/ClusterUpdateRequestBody.h 
    ./qpid/framing/ClusterConnectionDtxAckBody.cpp 
    ./qpid/framing/TxSelectBody.cpp 
    ./qpid/framing/DtxForgetBody.h 
    ./qpid/framing/SessionTimeoutBody.cpp 
    ./qpid/framing/ConnectionStartOkBody.h 
    ./qpid/framing/ConnectionSecureBody.cpp 
    ./qpid/framing/TypeCode.cpp 
    ./qpid/framing/ClusterConnectionQueueObserverStateBody.cpp 
    ./qpid/framing/ClusterConnectionShadowReadyBody.h 
    ./qpid/framing/Xid.cpp 
    ./qpid/framing/ClusterConnectionDeliveryRecordBody.h 
    ./qpid/framing/MessageResumeBody.h 
    ./qpid/framing/ServerInvoker.h 
    ./qpid/framing/AMQP_ServerProxy.h 
    ./qpid/framing/DtxEndBody.cpp 
    ./qpid/framing/SessionDetachBody.cpp 
    ./qpid/framing/ClusterConnectionOutputTaskBody.cpp 
    ./qpid/framing/ClusterConnectionDeliverCloseBody.cpp 
    ./qpid/framing/ConnectionHeartbeatBody.cpp 
    ./qpid/framing/ClusterConnectionTxEnqueueBody.h 
    ./qpid/framing/FileDeliverBody.cpp 
    ./qpid/framing/SessionAttachedBody.h 
    ./qpid/framing/QueuePurgeBody.cpp 
    ./qpid/framing/DtxGetTimeoutResult.cpp 
    ../include/qpid/framing/MessageResumeResult.h 
    ./qpid/framing/DtxEndBody.h 
    ./qpid/framing/ClusterConnectionConfigBody.h 
    ./qpid/framing/ClusterConnectionOutputTaskBody.h 
    ./qpid/framing/FileOpenBody.h 
    ./qpid/framing/ExecutionSyncBody.cpp 
    ./qpid/framing/QueueDeclareBody.cpp 
    ./qpid/framing/QueueQueryBody.h 
    ./qpid/framing/ClusterReadyBody.cpp 
    ./qpid/framing/TxRollbackBody.cpp 
    ./qpid/framing/ConnectionRedirectBody.h 
    ./qpid/framing/ExchangeUnbindBody.h 
    ./qpid/framing/SessionRequestTimeoutBody.cpp 
    ./qpid/framing/ExchangeBindBody.cpp 
    ./qpid/framing/ClusterConnectionDtxBufferRefBody.h 
    ./qpid/framing/ClusterConnectionTxStartBody.h 
    ./qpid/framing/FragmentProperties.cpp 
    ./qpid/framing/QueueDeleteBody.cpp 
    ./qpid/framing/MessageAcquireBody.cpp 
    ../include/qpid/framing/ExchangeBoundResult.h 
    ./qpid/framing/ClusterConnectionRetractOfferBody.cpp 
    ./qpid/framing/MessageFlushBody.cpp 
    ./qpid/framing/QueuePurgeBody.h 
    ./qpid/framing/MessageFlowBody.h 
    ./qpid/framing/SessionDetachBody.h 
    ./qpid/framing/MessageSetFlowModeBody.cpp 
    ./qpid/framing/ClusterConnectionTxAcceptBody.h 
    ./qpid/framing/ClusterRetractOfferBody.h 
    ./qpid/framing/AllInvoker.h 
    ./qpid/framing/ConnectionTuneOkBody.h 
    ./qpid/framing/MessageStopBody.cpp 
    ./qpid/framing/StreamReturnBody.h 
    ./qpid/framing/ConnectionCloseOkBody.cpp 
    ./qpid/framing/all_method_bodies.h 
    ./qpid/framing/AMQP_AllOperations.h 
    ./qpid/framing/ClusterConnectionShadowReadyBody.cpp 
    ./qpid/framing/ClusterConnectionTxAcceptBody.cpp 
    ./qpid/framing/ClusterDeliverToQueueBody.cpp 
    ./qpid/framing/SessionFlushBody.h 
    ./qpid/framing/ServerInvoker.cpp 
    ./qpid/framing/MessageCancelBody.cpp 
    ./qpid/framing/ClusterConnectionTxEndBody.cpp 
    ./qpid/framing/ClusterConnectionAbortBody.cpp 
    ./qpid/framing/ClusterTimerWakeupBody.h 
    ./qpid/framing/StreamConsumeOkBody.cpp 
    ./qpid/framing/FileReturnBody.h 
    ./qpid/framing/ClusterConnectionSessionStateBody.cpp 
    ./qpid/framing/DtxForgetBody.cpp 
    ./qpid/framing/SessionKnownCompletedBody.cpp 
    ./qpid/framing/ReplyTo.cpp 
    ./qpid/framing/MessageTransferBody.h 
    ./qpid/framing/SessionConfirmedBody.cpp 
    ./qpid/framing/ExecutionSyncBody.h 
    ./qpid/framing/DtxRollbackBody.cpp 
    ./qpid/framing/ConnectionTuneOkBody.cpp 
    ./qpid/framing/StreamConsumeBody.cpp 
    ./qpid/framing/ConnectionSecureOkBody.h 
    ./qpid/framing/DtxPrepareBody.h 
    ./qpid/framing/MessageProperties.cpp 
    ./qpid/framing/ExecutionResultBody.cpp 
    ./qpid/framing/ExchangeQueryBody.h 
    ./qpid/framing/ClusterShutdownBody.h 
    ./qpid/framing/SessionExpectedBody.cpp 
    ./qpid/framing/AMQP_ServerOperations.h 
    ../include/qpid/framing/amqp_structs.h 
    ./qpid/framing/ClusterConnectionTxStartBody.cpp 
    ./qpid/framing/FileOpenBody.cpp 
    ./qpid/framing/MessageReleaseBody.cpp 
    ./qpid/framing/SessionGapBody.h 
    ./qpid/framing/ConnectionStartBody.h 
    ./qpid/framing/Header.cpp 
    ./qpid/framing/StreamProperties.cpp 
    ./qpid/framing/MethodBodyDefaultVisitor.h 
    ./qpid/framing/ClusterConnectionShadowPrepareBody.h 
    ./qpid/framing/ClusterErrorCheckBody.cpp 
    ./qpid/framing/AMQP_ClientProxy.cpp 
    ./qpid/framing/DtxSelectBody.cpp 
    ./qpid/framing/ClusterConnectionManagementSetupStateBody.h 
    ./qpid/framing/SessionDetachedBody.cpp 
    ./qpid/framing/ClusterConnectionDtxWorkRecordBody.cpp 
    ./qpid/framing/StreamReturnBody.cpp 
    ./qpid/framing/SessionCommandPointBody.cpp 
    ./qpid/framing/FileQosBody.cpp 
    ./qpid/framing/FileProperties.cpp 
    ./qpid/framing/DtxGetTimeoutBody.cpp 
    ./qpid/framing/MessageSetFlowModeBody.h 
    ./qpid/framing/ClusterTimerDropBody.cpp 
    ./qpid/framing/ExchangeDeclareBody.cpp 
    ./qpid/framing/ExecutionResultBody.h 
    ./qpid/framing/ClusterConnectionClockBody.cpp 
    ./qpid/framing/ClusterConnectionAddQueueListenerBody.h 
    ./qpid/framing/ClusterConnectionRetractOfferBody.h 
    ./qpid/framing/ClusterConnectionDtxStartBody.cpp 
    ./qpid/framing/ClusterConnectionAccumulatedAckBody.h 
    ./qpid/framing/ClusterConnectionShadowPrepareBody.cpp 
    ./qpid/framing/ClusterConnectionAnnounceBody.cpp 
    ./qpid/framing/DtxGetTimeoutBody.h 
    ./qpid/framing/ExecutionExceptionBody.h 
    ./qpid/framing/ClusterDeliverToQueueBody.h 
    ./qpid/framing/FileConsumeBody.h 
    ./qpid/framing/SessionCommandPointBody.h 
    ./qpid/framing/SessionCompletedBody.cpp 
    ./qpid/framing/ClusterConnectionQueueObserverStateBody.h 
    ./qpid/framing/ClusterConnectionQueuePositionBody.cpp 
    ../include/qpid/framing/QueueQueryResult.h 
    ./qpid/framing/MessageAcquireResult.cpp 
    ./qpid/framing/TxRollbackBody.h 
    ./qpid/framing/ClusterConnectionQueueDequeueSincePurgeStateBody.cpp 
    ./qpid/framing/ClusterConfigChangeBody.h 
    ./qpid/framing/ConnectionSecureBody.h 
    ./qpid/framing/ConnectionHeartbeatBody.h 
    ./qpid/framing/StreamCancelBody.cpp 
    ../include/qpid/framing/MessageAcquireResult.h 
    ./qpid/framing/ConnectionRedirectBody.cpp 
    ../include/qpid/framing/ExchangeQueryResult.h 
    ./qpid/framing/MessageResumeBody.cpp 
    ./qpid/framing/MessageCancelBody.h 
    ./qpid/framing/StreamQosOkBody.cpp 
    ./qpid/framing/SessionExpectedBody.h 
    ./qpid/framing/ExchangeBoundResult.cpp 
    ./qpid/framing/DtxRecoverBody.cpp 
    ../include/qpid/framing/TypeCode.h 
    ./qpid/framing/ClusterConnectionConsumerStateBody.cpp 
    ./qpid/framing/ClusterConnectionShadowSetUserBody.h 
    ./qpid/framing/ConnectionOpenOkBody.h 
    ./qpid/framing/MessageReleaseBody.h 
    ./qpid/framing/ConnectionOpenBody.h 
    ./qpid/framing/StreamPublishBody.cpp 
    ./qpid/framing/ClusterConnectionMembershipBody.cpp 
    ./qpid/framing/ClusterConnectionTxPublishBody.h 
    ./qpid/framing/MessageRejectBody.cpp 
    ./qpid/framing/ClusterConnectionExchangeBody.h 
    ./qpid/framing/ClusterConnectionConsumerStateBody.h 
    ./qpid/framing/ClusterClockBody.cpp 
    ./qpid/framing/ClusterReadyBody.h 
    ./qpid/framing/MessageResumeResult.cpp 
    ./qpid/framing/DtxStartBody.cpp 
    ./qpid/framing/ClusterConnectionClockBody.h 
    ./qpid/framing/ClusterConnectionDeliveryRecordBody.cpp 
    ./qpid/framing/ClusterConnectionDeliverDoOutputBody.h 
    ./qpid/framing/MessageSubscribeBody.h 
    ./qpid/framing/DtxRollbackBody.h 
    ./qpid/framing/ConnectionStartOkBody.cpp)

set(rgen_amqp_0_10_srcs ./qpid/amqp_0_10/StructVisitor.h 
    ./qpid/amqp_0_10/ApplyStruct.h 
    ./qpid/amqp_0_10/CommandHolder.cpp 
    ./qpid/amqp_0_10/specification_fwd.h 
    ./qpid/amqp_0_10/structs.h 
    ./qpid/amqp_0_10/exceptions.h 
    ./qpid/amqp_0_10/ProxyTemplate.h 
    ./qpid/amqp_0_10/structs.cpp 
    ./qpid/amqp_0_10/StructHolder.cpp 
    ./qpid/amqp_0_10/ApplyCommand.h 
    ./qpid/amqp_0_10/TypeForCode.h 
    ./qpid/amqp_0_10/ControlVisitor.h 
    ./qpid/amqp_0_10/ControlHolder.h 
    ./qpid/amqp_0_10/specification.h 
    ./qpid/amqp_0_10/CodeForType.h 
    ./qpid/amqp_0_10/StructHolder.h 
    ./qpid/amqp_0_10/ApplyControl.h 
    ./qpid/amqp_0_10/TypeForCode.cpp 
    ./qpid/amqp_0_10/ControlHolder.cpp 
    ./qpid/amqp_0_10/CommandVisitor.h 
    ./qpid/amqp_0_10/specification.cpp 
    ./qpid/amqp_0_10/handlers.h 
    ./qpid/amqp_0_10/CommandHolder.h 
    ./qpid/amqp_0_10/CodeForType.cpp)
set(rgen_srcs ./qpid/amqp_0_10/StructVisitor.h 
    ./qpid/framing/MethodBodyDefaultVisitor.cpp 
    ./qpid/framing/FileReturnBody.cpp 
    ../include/qpid/framing/ReplyTo.h 
    ./qpid/framing/DtxRecoverResult.cpp 
    ./qpid/framing/ConnectionCloseBody.cpp 
    ./qpid/framing/FileConsumeOkBody.h 
    ./qpid/framing/TxCommitBody.cpp 
    ./qpid/framing/SessionKnownCompletedBody.h 
    ./qpid/framing/MessageAcquireBody.h 
    ./qpid/framing/DtxSetTimeoutBody.cpp 
    ../include/qpid/client/AsyncSession_0_10.h 
    ./qpid/framing/ClusterConnectionConfigBody.cpp 
    ./qpid/framing/ClusterConnectionTxDequeueBody.h 
    ./qpid/framing/ClusterUpdateRequestBody.cpp 
    ./qpid/framing/ExchangeBoundBody.h 
    ../include/qpid/framing/Xid.h 
    ./qpid/framing/SessionGapBody.cpp 
    ./qpid/framing/StreamQosBody.h 
    ./qpid/framing/StreamCancelBody.h 
    ./qpid/framing/ClusterInitialStatusBody.h 
    ./qpid/framing/SessionCompletedBody.h 
    ./qpid/framing/ClusterConnectionDtxWorkRecordBody.h 
    ./qpid/framing/ClusterTimerDropBody.h 
    ./qpid/framing/ConnectionTuneBody.h 
    ./qpid/framing/DtxPrepareBody.cpp 
    ./qpid/amqp_0_10/ApplyStruct.h 
    ./qpid/framing/ClusterConnectionTxPublishBody.cpp 
    ./qpid/framing/MessageRejectBody.h 
    ./qpid/framing/DeliveryProperties.cpp 
    ./qpid/framing/StreamDeliverBody.h 
    ./qpid/framing/MethodBodyConstVisitor.h 
    ./qpid/framing/ClusterRetractOfferBody.cpp 
    ./qpid/framing/SessionTimeoutBody.h 
    ./qpid/framing/FileRejectBody.h 
    ./qpid/framing/StreamPublishBody.h 
    ./qpid/framing/DtxCommitBody.cpp 
    ./qpid/framing/AMQP_ServerProxy.cpp 
    ./qpid/framing/FilePublishBody.cpp 
    ./qpid/framing/ClusterConnectionAddQueueListenerBody.cpp 
    ./qpid/framing/ClusterConnectionDtxAckBody.h 
    ./qpid/framing/FileStageBody.cpp 
    ./qpid/framing/ClusterConnectionTxEndBody.h 
    ./qpid/framing/ClusterConnectionDtxEndBody.cpp 
    ./qpid/framing/SessionDetachedBody.h 
    ../include/qpid/framing/DtxRecoverResult.h 
    ./qpid/framing/QueueQueryResult.cpp 
    ./qpid/framing/ExchangeQueryBody.cpp 
    ./qpid/framing/SessionAttachBody.h 
    ./qpid/framing/ClusterConnectionShadowSetUserBody.cpp 
    ./qpid/framing/StreamQosOkBody.h 
    ./qpid/framing/FileOpenOkBody.h 
    ./qpid/framing/SessionAttachBody.cpp 
    ../include/qpid/client/no_keyword/AsyncSession_0_10.h 
    ./qpid/framing/ClusterConnectionQueueDequeueSincePurgeStateBody.h 
    ../include/qpid/framing/DtxGetTimeoutResult.h 
    ./qpid/framing/FileQosBody.h 
    ./qpid/framing/SessionRequestTimeoutBody.h 
    ./qpid/amqp_0_10/CommandHolder.cpp 
    ./qpid/amqp_0_10/specification_fwd.h 
    ./qpid/framing/ClusterConnectionTxDequeueBody.cpp 
    ./qpid/framing/ExchangeUnbindBody.cpp 
    ./qpid/framing/SessionAttachedBody.cpp 
    ./qpid/framing/SessionFlushBody.cpp 
    ./qpid/framing/ClusterConnectionExchangeBody.cpp 
    ./qpid/framing/ExchangeDeleteBody.h 
    ./qpid/framing/FileCancelBody.cpp 
    ./qpid/framing/MessageFlushBody.h 
    ./qpid/framing/ConnectionSecureOkBody.cpp 
    ./qpid/framing/DtxSetTimeoutBody.h 
    ./qpid/framing/FileRejectBody.cpp 
    ../include/qpid/framing/Header.h 
    ../include/qpid/framing/StreamProperties.h 
    ./qpid/framing/AMQP_AllProxy.h 
    ./qpid/amqp_0_10/structs.h 
    ./qpid/framing/ClusterConnectionDtxStartBody.h 
    ./qpid/framing/AllInvoker.cpp 
    ./qpid/framing/FileDeliverBody.h 
    ./qpid/framing/AMQP_ClientOperations.h 
    ./qpid/framing/ClusterConnectionQueuePositionBody.h 
    ./qpid/framing/ClusterConnectionMembershipBody.h 
    ./qpid/client/no_keyword/AsyncSession_0_10.cpp 
    ./qpid/framing/ClusterConnectionSessionStateBody.h 
    ./qpid/framing/ClusterConnectionDtxEndBody.h 
    ./qpid/framing/ClusterConnectionDeliverDoOutputBody.cpp 
    ./qpid/framing/ClusterConnectionDeliverCloseBody.h 
    ./qpid/framing/ClusterConnectionAnnounceBody.h 
    ./qpid/framing/ClusterClockBody.h 
    ./qpid/framing/DtxSelectBody.h 
    ./qpid/framing/TxSelectBody.h 
    ../include/qpid/framing/reply_exceptions.h 
    ./qpid/framing/ClusterErrorCheckBody.h 
    ./qpid/framing/SessionConfirmedBody.h 
    ./qpid/framing/MessageFlowBody.cpp 
    ./qpid/framing/StreamQosBody.cpp 
    ./qpid/framing/DtxCommitBody.h 
    ./qpid/framing/ExchangeBoundBody.cpp 
    ./qpid/framing/ExchangeBindBody.h 
    ./qpid/framing/frame_body_lists.h 
    ./qpid/framing/FileConsumeOkBody.cpp 
    ../include/qpid/framing/FragmentProperties.h 
    ./qpid/framing/ClusterUpdateOfferBody.h 
    ./qpid/framing/MessageTransferBody.cpp 
    ./qpid/framing/FileQosOkBody.h 
    ./qpid/framing/ClusterShutdownBody.cpp 
    ./qpid/framing/StreamDeliverBody.cpp 
    ../include/qpid/framing/FileProperties.h 
    ./qpid/framing/ExchangeDeleteBody.cpp 
    ./qpid/framing/ConnectionTuneBody.cpp 
    ./qpid/framing/ExchangeQueryResult.cpp 
    ./qpid/framing/TxCommitBody.h 
    ./qpid/framing/ClientInvoker.h 
    ./qpid/framing/ClusterUpdateOfferBody.cpp 
    ./qpid/framing/reply_exceptions.cpp 
    ./qpid/framing/ClusterConnectionQueueFairshareStateBody.cpp 
    ./qpid/framing/QueueDeclareBody.h 
    ./qpid/framing/StreamConsumeOkBody.h 
    ./qpid/amqp_0_10/exceptions.h 
    ../include/qpid/framing/constants.h 
    ./qpid/framing/ClusterConnectionManagementSetupStateBody.cpp 
    ./qpid/framing/FilePublishBody.h 
    ./qpid/framing/ConnectionCloseBody.h 
    ./qpid/framing/ConnectionOpenOkBody.cpp 
    ./qpid/framing/ClusterConnectionAbortBody.h 
    ./qpid/framing/ClusterInitialStatusBody.cpp 
    ../include/qpid/framing/XaResult.h 
    ./qpid/framing/XaResult.cpp 
    ./qpid/framing/FileStageBody.h 
    ./qpid/framing/FileAckBody.h 
    ./qpid/amqp_0_10/ProxyTemplate.h 
    ../include/qpid/framing/MessageProperties.h 
    ./qpid/framing/FileQosOkBody.cpp 
    ./qpid/framing/ClusterTimerWakeupBody.cpp 
    ./qpid/framing/ConnectionOpenBody.cpp 
    ./qpid/framing/FileOpenOkBody.cpp 
    ./qpid/framing/StreamConsumeBody.h 
    ./qpid/framing/AMQP_ClientProxy.h 
    ./qpid/framing/QueueDeleteBody.h 
    ./qpid/framing/FileCancelBody.h 
    ./qpid/framing/MessageSubscribeBody.cpp 
    ./qpid/amqp_0_10/structs.cpp 
    ../include/qpid/framing/enum.h 
    ./qpid/framing/ClusterConnectionQueueFairshareStateBody.h 
    ./qpid/framing/ClusterConnectionDtxBufferRefBody.cpp 
    ./qpid/framing/ClusterConnectionAccumulatedAckBody.cpp 
    ./qpid/framing/MessageAcceptBody.h 
    ./qpid/framing/AMQP_AllProxy.cpp 
    ./qpid/framing/FileConsumeBody.cpp 
    ./qpid/framing/ExecutionExceptionBody.cpp 
    ./qpid/framing/ConnectionCloseOkBody.h 
    ./qpid/framing/ClusterConnectionTxEnqueueBody.cpp 
    ./qpid/framing/ClusterConfigChangeBody.cpp 
    ./qpid/framing/ConnectionStartBody.cpp 
    ./qpid/framing/DtxRecoverBody.h 
    ./qpid/framing/DtxStartBody.h 
    ./qpid/framing/MessageStopBody.h 
    ./qpid/framing/ClientInvoker.cpp 
    ./qpid/amqp_0_10/StructHolder.cpp 
    ./qpid/framing/MethodBodyFactory.cpp 
    ./qpid/framing/MessageAcceptBody.cpp 
    ../include/qpid/framing/DeliveryProperties.h 
    ./qpid/framing/FileAckBody.cpp 
    ./qpid/framing/QueueQueryBody.cpp 
    ./qpid/framing/ExchangeDeclareBody.h 
    ./qpid/framing/ClusterUpdateRequestBody.h 
    ./qpid/framing/ClusterConnectionDtxAckBody.cpp 
    ./qpid/framing/TxSelectBody.cpp 
    ./qpid/framing/DtxForgetBody.h 
    ./qpid/framing/SessionTimeoutBody.cpp 
    ./qpid/framing/ConnectionStartOkBody.h 
    ./qpid/framing/ConnectionSecureBody.cpp 
    ./qpid/framing/TypeCode.cpp 
    ./qpid/framing/ClusterConnectionQueueObserverStateBody.cpp 
    ./qpid/framing/ClusterConnectionShadowReadyBody.h 
    ./qpid/framing/Xid.cpp 
    ./qpid/framing/ClusterConnectionDeliveryRecordBody.h 
    ./qpid/framing/MessageResumeBody.h 
    ./qpid/framing/ServerInvoker.h 
    ./qpid/framing/AMQP_ServerProxy.h 
    ./qpid/framing/DtxEndBody.cpp 
    ./qpid/framing/SessionDetachBody.cpp 
    ./qpid/framing/ClusterConnectionOutputTaskBody.cpp 
    ./qpid/framing/ClusterConnectionDeliverCloseBody.cpp 
    ./qpid/framing/ConnectionHeartbeatBody.cpp 
    ./qpid/framing/ClusterConnectionTxEnqueueBody.h 
    ./qpid/framing/FileDeliverBody.cpp 
    ./qpid/framing/SessionAttachedBody.h 
    ./qpid/framing/QueuePurgeBody.cpp 
    ./qpid/framing/DtxGetTimeoutResult.cpp 
    ../include/qpid/framing/MessageResumeResult.h 
    ./qpid/framing/DtxEndBody.h 
    ./qpid/framing/ClusterConnectionConfigBody.h 
    ./qpid/framing/ClusterConnectionOutputTaskBody.h 
    ./qpid/framing/FileOpenBody.h 
    ./qpid/framing/ExecutionSyncBody.cpp 
    ./qpid/framing/QueueDeclareBody.cpp 
    ./qpid/framing/QueueQueryBody.h 
    ./qpid/amqp_0_10/ApplyCommand.h 
    ./qpid/framing/ClusterReadyBody.cpp 
    ./qpid/framing/TxRollbackBody.cpp 
    ./qpid/framing/ConnectionRedirectBody.h 
    ./qpid/framing/ExchangeUnbindBody.h 
    ./qpid/framing/SessionRequestTimeoutBody.cpp 
    ./qpid/framing/ExchangeBindBody.cpp 
    ./qpid/amqp_0_10/TypeForCode.h 
    ../include/qpid/client/no_keyword/Session_0_10.h 
    ./qpid/framing/ClusterConnectionDtxBufferRefBody.h 
    ./qpid/framing/ClusterConnectionTxStartBody.h 
    ./qpid/framing/FragmentProperties.cpp 
    ./qpid/framing/QueueDeleteBody.cpp 
    ./qpid/framing/MessageAcquireBody.cpp 
    ../include/qpid/framing/ExchangeBoundResult.h 
    ./qpid/amqp_0_10/ControlVisitor.h 
    ./qpid/amqp_0_10/ControlHolder.h 
    ./qpid/framing/ClusterConnectionRetractOfferBody.cpp 
    ./qpid/framing/MessageFlushBody.cpp 
    ./qpid/framing/QueuePurgeBody.h 
    ./qpid/framing/MessageFlowBody.h 
    ./qpid/framing/SessionDetachBody.h 
    ./qpid/framing/MessageSetFlowModeBody.cpp 
    ./qpid/amqp_0_10/specification.h 
    ./qpid/amqp_0_10/CodeForType.h 
    ./qpid/framing/ClusterConnectionTxAcceptBody.h 
    ./qpid/framing/ClusterRetractOfferBody.h 
    ./qpid/framing/AllInvoker.h 
    ./qpid/framing/ConnectionTuneOkBody.h 
    ./qpid/framing/MessageStopBody.cpp 
    ./qpid/framing/StreamReturnBody.h 
    ./qpid/framing/ConnectionCloseOkBody.cpp 
    ./qpid/framing/all_method_bodies.h 
    ./qpid/framing/AMQP_AllOperations.h 
    ./qpid/framing/ClusterConnectionShadowReadyBody.cpp 
    ./qpid/framing/ClusterConnectionTxAcceptBody.cpp 
    ./qpid/framing/ClusterDeliverToQueueBody.cpp 
    ./qpid/framing/SessionFlushBody.h 
    ./qpid/framing/ServerInvoker.cpp 
    ./qpid/framing/MessageCancelBody.cpp 
    ./qpid/amqp_0_10/StructHolder.h 
    ./qpid/framing/ClusterConnectionTxEndBody.cpp 
    ./qpid/framing/ClusterConnectionAbortBody.cpp 
    ./qpid/framing/ClusterTimerWakeupBody.h 
    ./qpid/framing/StreamConsumeOkBody.cpp 
    ./qpid/framing/FileReturnBody.h 
    ./qpid/framing/ClusterConnectionSessionStateBody.cpp 
    ./qpid/framing/DtxForgetBody.cpp 
    ./qpid/framing/SessionKnownCompletedBody.cpp 
    ./qpid/framing/ReplyTo.cpp 
    ./qpid/framing/MessageTransferBody.h 
    ./qpid/framing/SessionConfirmedBody.cpp 
    ./qpid/framing/ExecutionSyncBody.h 
    ./qpid/framing/DtxRollbackBody.cpp 
    ./qpid/framing/ConnectionTuneOkBody.cpp 
    ./qpid/framing/StreamConsumeBody.cpp 
    ./qpid/framing/ConnectionSecureOkBody.h 
    ./qpid/framing/DtxPrepareBody.h 
    ./qpid/framing/MessageProperties.cpp 
    ./qpid/framing/ExecutionResultBody.cpp 
    ./qpid/framing/ExchangeQueryBody.h 
    ./qpid/framing/ClusterShutdownBody.h 
    ./qpid/framing/SessionExpectedBody.cpp 
    ./qpid/amqp_0_10/ApplyControl.h 
    ./qpid/framing/AMQP_ServerOperations.h 
    ../include/qpid/framing/amqp_structs.h 
    ./qpid/framing/ClusterConnectionTxStartBody.cpp 
    ./qpid/framing/FileOpenBody.cpp 
    ./qpid/framing/MessageReleaseBody.cpp 
    ./qpid/framing/SessionGapBody.h 
    ./qpid/framing/ConnectionStartBody.h 
    ./qpid/framing/Header.cpp 
    ./qpid/framing/StreamProperties.cpp 
    ./qpid/framing/MethodBodyDefaultVisitor.h 
    ./qpid/framing/ClusterConnectionShadowPrepareBody.h 
    ./qpid/framing/ClusterErrorCheckBody.cpp 
    ./qpid/framing/AMQP_ClientProxy.cpp 
    ./qpid/framing/DtxSelectBody.cpp 
    ../include/qpid/client/Session_0_10.h 
    ./qpid/framing/ClusterConnectionManagementSetupStateBody.h 
    ./qpid/framing/SessionDetachedBody.cpp 
    ./qpid/amqp_0_10/TypeForCode.cpp 
    ../include/qpid/client/arg.h 
    ./qpid/framing/ClusterConnectionDtxWorkRecordBody.cpp 
    ./qpid/framing/StreamReturnBody.cpp 
    ./qpid/framing/SessionCommandPointBody.cpp 
    ./qpid/framing/FileQosBody.cpp 
    ./qpid/framing/FileProperties.cpp 
    ./qpid/framing/DtxGetTimeoutBody.cpp 
    ./qpid/framing/MessageSetFlowModeBody.h 
    ./qpid/framing/ClusterTimerDropBody.cpp 
    ./qpid/framing/ExchangeDeclareBody.cpp 
    ./qpid/framing/ExecutionResultBody.h 
    ./qpid/framing/ClusterConnectionClockBody.cpp 
    ./qpid/framing/ClusterConnectionAddQueueListenerBody.h 
    ./qpid/framing/ClusterConnectionRetractOfferBody.h 
    ./qpid/framing/ClusterConnectionDtxStartBody.cpp 
    ./qpid/framing/ClusterConnectionAccumulatedAckBody.h 
    ./qpid/framing/ClusterConnectionShadowPrepareBody.cpp 
    ./qpid/framing/ClusterConnectionAnnounceBody.cpp 
    ./qpid/framing/DtxGetTimeoutBody.h 
    ./qpid/framing/ExecutionExceptionBody.h 
    ./qpid/framing/ClusterDeliverToQueueBody.h 
    ./qpid/framing/FileConsumeBody.h 
    ./qpid/framing/SessionCommandPointBody.h 
    ./qpid/framing/SessionCompletedBody.cpp 
    ./qpid/framing/ClusterConnectionQueueObserverStateBody.h 
    ./qpid/client/no_keyword/Session_0_10.cpp 
    ./qpid/framing/ClusterConnectionQueuePositionBody.cpp 
    ../include/qpid/framing/QueueQueryResult.h 
    ./qpid/amqp_0_10/ControlHolder.cpp 
    ./qpid/framing/MessageAcquireResult.cpp 
    ./qpid/framing/TxRollbackBody.h 
    ./qpid/amqp_0_10/CommandVisitor.h 
    ./qpid/framing/ClusterConnectionQueueDequeueSincePurgeStateBody.cpp 
    ./qpid/framing/ClusterConfigChangeBody.h 
    ./qpid/framing/ConnectionSecureBody.h 
    ./qpid/framing/ConnectionHeartbeatBody.h 
    ./qpid/framing/StreamCancelBody.cpp 
    ../include/qpid/framing/MessageAcquireResult.h 
    ./qpid/framing/ConnectionRedirectBody.cpp 
    ../include/qpid/framing/ExchangeQueryResult.h 
    ./qpid/framing/MessageResumeBody.cpp 
    ./qpid/framing/MessageCancelBody.h 
    ./qpid/framing/StreamQosOkBody.cpp 
    ./qpid/framing/SessionExpectedBody.h 
    ./qpid/amqp_0_10/specification.cpp 
    ./qpid/framing/ExchangeBoundResult.cpp 
    ./qpid/framing/DtxRecoverBody.cpp 
    ../include/qpid/framing/TypeCode.h 
    ./qpid/framing/ClusterConnectionConsumerStateBody.cpp 
    ./qpid/framing/ClusterConnectionShadowSetUserBody.h 
    ./qpid/framing/ConnectionOpenOkBody.h 
    ./qpid/framing/MessageReleaseBody.h 
    ./qpid/framing/ConnectionOpenBody.h 
    ./qpid/framing/StreamPublishBody.cpp 
    ./qpid/amqp_0_10/handlers.h 
    ./qpid/framing/ClusterConnectionMembershipBody.cpp 
    ./qpid/framing/ClusterConnectionTxPublishBody.h 
    ./qpid/framing/MessageRejectBody.cpp 
    ./qpid/amqp_0_10/CommandHolder.h 
    ./tests/allSegmentTypes.h 
    ./qpid/framing/ClusterConnectionExchangeBody.h 
    ./qpid/framing/ClusterConnectionConsumerStateBody.h 
    ./qpid/framing/ClusterClockBody.cpp 
    ./qpid/framing/ClusterReadyBody.h 
    ./qpid/framing/MessageResumeResult.cpp 
    ./qpid/framing/DtxStartBody.cpp 
    ./qpid/amqp_0_10/CodeForType.cpp 
    ./qpid/framing/ClusterConnectionClockBody.h 
    ./qpid/framing/ClusterConnectionDeliveryRecordBody.cpp 
    ./qpid/framing/ClusterConnectionDeliverDoOutputBody.h 
    ./qpid/framing/MessageSubscribeBody.h 
    ./qpid/framing/DtxRollbackBody.h 
    ./qpid/framing/ConnectionStartOkBody.cpp)

# Header file install rules.
set(qpid_amqp_0_10dir  ${includedir}/qpid/amqp_0_10)
set(dist_qpid_amqp_0_10_HEADERS ./qpid/amqp_0_10/StructVisitor.h 
    ./qpid/amqp_0_10/ApplyStruct.h 
    ./qpid/amqp_0_10/specification_fwd.h 
    ./qpid/amqp_0_10/structs.h 
    ./qpid/amqp_0_10/exceptions.h 
    ./qpid/amqp_0_10/ProxyTemplate.h 
    ./qpid/amqp_0_10/ApplyCommand.h 
    ./qpid/amqp_0_10/TypeForCode.h 
    ./qpid/amqp_0_10/ControlVisitor.h 
    ./qpid/amqp_0_10/ControlHolder.h 
    ./qpid/amqp_0_10/specification.h 
    ./qpid/amqp_0_10/CodeForType.h 
    ./qpid/amqp_0_10/StructHolder.h 
    ./qpid/amqp_0_10/ApplyControl.h 
    ./qpid/amqp_0_10/CommandVisitor.h 
    ./qpid/amqp_0_10/handlers.h 
    ./qpid/amqp_0_10/CommandHolder.h)

set(qpid_framingdir  ${includedir}/qpid/framing)
set(dist_qpid_framing_HEADERS ../include/qpid/framing/ReplyTo.h 
    ./qpid/framing/FileConsumeOkBody.h 
    ./qpid/framing/SessionKnownCompletedBody.h 
    ./qpid/framing/MessageAcquireBody.h 
    ./qpid/framing/ClusterConnectionTxDequeueBody.h 
    ./qpid/framing/ExchangeBoundBody.h 
    ../include/qpid/framing/Xid.h 
    ./qpid/framing/StreamQosBody.h 
    ./qpid/framing/StreamCancelBody.h 
    ./qpid/framing/ClusterInitialStatusBody.h 
    ./qpid/framing/SessionCompletedBody.h 
    ./qpid/framing/ClusterConnectionDtxWorkRecordBody.h 
    ./qpid/framing/ClusterTimerDropBody.h 
    ./qpid/framing/ConnectionTuneBody.h 
    ./qpid/framing/MessageRejectBody.h 
    ./qpid/framing/StreamDeliverBody.h 
    ./qpid/framing/MethodBodyConstVisitor.h 
    ./qpid/framing/SessionTimeoutBody.h 
    ./qpid/framing/FileRejectBody.h 
    ./qpid/framing/StreamPublishBody.h 
    ./qpid/framing/ClusterConnectionDtxAckBody.h 
    ./qpid/framing/ClusterConnectionTxEndBody.h 
    ./qpid/framing/SessionDetachedBody.h 
    ../include/qpid/framing/DtxRecoverResult.h 
    ./qpid/framing/SessionAttachBody.h 
    ./qpid/framing/StreamQosOkBody.h 
    ./qpid/framing/FileOpenOkBody.h 
    ./qpid/framing/ClusterConnectionQueueDequeueSincePurgeStateBody.h 
    ../include/qpid/framing/DtxGetTimeoutResult.h 
    ./qpid/framing/FileQosBody.h 
    ./qpid/framing/SessionRequestTimeoutBody.h 
    ./qpid/framing/ExchangeDeleteBody.h 
    ./qpid/framing/MessageFlushBody.h 
    ./qpid/framing/DtxSetTimeoutBody.h 
    ../include/qpid/framing/Header.h 
    ../include/qpid/framing/StreamProperties.h 
    ./qpid/framing/AMQP_AllProxy.h 
    ./qpid/framing/ClusterConnectionDtxStartBody.h 
    ./qpid/framing/FileDeliverBody.h 
    ./qpid/framing/AMQP_ClientOperations.h 
    ./qpid/framing/ClusterConnectionQueuePositionBody.h 
    ./qpid/framing/ClusterConnectionMembershipBody.h 
    ./qpid/framing/ClusterConnectionSessionStateBody.h 
    ./qpid/framing/ClusterConnectionDtxEndBody.h 
    ./qpid/framing/ClusterConnectionDeliverCloseBody.h 
    ./qpid/framing/ClusterConnectionAnnounceBody.h 
    ./qpid/framing/ClusterClockBody.h 
    ./qpid/framing/DtxSelectBody.h 
    ./qpid/framing/TxSelectBody.h 
    ../include/qpid/framing/reply_exceptions.h 
    ./qpid/framing/ClusterErrorCheckBody.h 
    ./qpid/framing/SessionConfirmedBody.h 
    ./qpid/framing/DtxCommitBody.h 
    ./qpid/framing/ExchangeBindBody.h 
    ./qpid/framing/frame_body_lists.h 
    ../include/qpid/framing/FragmentProperties.h 
    ./qpid/framing/ClusterUpdateOfferBody.h 
    ./qpid/framing/FileQosOkBody.h 
    ../include/qpid/framing/FileProperties.h 
    ./qpid/framing/TxCommitBody.h 
    ./qpid/framing/ClientInvoker.h 
    ./qpid/framing/QueueDeclareBody.h 
    ./qpid/framing/StreamConsumeOkBody.h 
    ../include/qpid/framing/constants.h 
    ./qpid/framing/FilePublishBody.h 
    ./qpid/framing/ConnectionCloseBody.h 
    ./qpid/framing/ClusterConnectionAbortBody.h 
    ../include/qpid/framing/XaResult.h 
    ./qpid/framing/FileStageBody.h 
    ./qpid/framing/FileAckBody.h 
    ../include/qpid/framing/MessageProperties.h 
    ./qpid/framing/StreamConsumeBody.h 
    ./qpid/framing/AMQP_ClientProxy.h 
    ./qpid/framing/QueueDeleteBody.h 
    ./qpid/framing/FileCancelBody.h 
    ../include/qpid/framing/enum.h 
    ./qpid/framing/ClusterConnectionQueueFairshareStateBody.h 
    ./qpid/framing/MessageAcceptBody.h 
    ./qpid/framing/ConnectionCloseOkBody.h 
    ./qpid/framing/DtxRecoverBody.h 
    ./qpid/framing/DtxStartBody.h 
    ./qpid/framing/MessageStopBody.h 
    ../include/qpid/framing/DeliveryProperties.h 
    ./qpid/framing/ExchangeDeclareBody.h 
    ./qpid/framing/ClusterUpdateRequestBody.h 
    ./qpid/framing/DtxForgetBody.h 
    ./qpid/framing/ConnectionStartOkBody.h 
    ./qpid/framing/ClusterConnectionShadowReadyBody.h 
    ./qpid/framing/ClusterConnectionDeliveryRecordBody.h 
    ./qpid/framing/MessageResumeBody.h 
    ./qpid/framing/ServerInvoker.h 
    ./qpid/framing/AMQP_ServerProxy.h 
    ./qpid/framing/ClusterConnectionTxEnqueueBody.h 
    ./qpid/framing/SessionAttachedBody.h 
    ../include/qpid/framing/MessageResumeResult.h 
    ./qpid/framing/DtxEndBody.h 
    ./qpid/framing/ClusterConnectionConfigBody.h 
    ./qpid/framing/ClusterConnectionOutputTaskBody.h 
    ./qpid/framing/FileOpenBody.h 
    ./qpid/framing/QueueQueryBody.h 
    ./qpid/framing/ConnectionRedirectBody.h 
    ./qpid/framing/ExchangeUnbindBody.h 
    ./qpid/framing/ClusterConnectionDtxBufferRefBody.h 
    ./qpid/framing/ClusterConnectionTxStartBody.h 
    ../include/qpid/framing/ExchangeBoundResult.h 
    ./qpid/framing/QueuePurgeBody.h 
    ./qpid/framing/MessageFlowBody.h 
    ./qpid/framing/SessionDetachBody.h 
    ./qpid/framing/ClusterConnectionTxAcceptBody.h 
    ./qpid/framing/ClusterRetractOfferBody.h 
    ./qpid/framing/AllInvoker.h 
    ./qpid/framing/ConnectionTuneOkBody.h 
    ./qpid/framing/StreamReturnBody.h 
    ./qpid/framing/all_method_bodies.h 
    ./qpid/framing/AMQP_AllOperations.h 
    ./qpid/framing/SessionFlushBody.h 
    ./qpid/framing/ClusterTimerWakeupBody.h 
    ./qpid/framing/FileReturnBody.h 
    ./qpid/framing/MessageTransferBody.h 
    ./qpid/framing/ExecutionSyncBody.h 
    ./qpid/framing/ConnectionSecureOkBody.h 
    ./qpid/framing/DtxPrepareBody.h 
    ./qpid/framing/ExchangeQueryBody.h 
    ./qpid/framing/ClusterShutdownBody.h 
    ./qpid/framing/AMQP_ServerOperations.h 
    ../include/qpid/framing/amqp_structs.h 
    ./qpid/framing/SessionGapBody.h 
    ./qpid/framing/ConnectionStartBody.h 
    ./qpid/framing/MethodBodyDefaultVisitor.h 
    ./qpid/framing/ClusterConnectionShadowPrepareBody.h 
    ./qpid/framing/ClusterConnectionManagementSetupStateBody.h 
    ./qpid/framing/MessageSetFlowModeBody.h 
    ./qpid/framing/ExecutionResultBody.h 
    ./qpid/framing/ClusterConnectionAddQueueListenerBody.h 
    ./qpid/framing/ClusterConnectionRetractOfferBody.h 
    ./qpid/framing/ClusterConnectionAccumulatedAckBody.h 
    ./qpid/framing/DtxGetTimeoutBody.h 
    ./qpid/framing/ExecutionExceptionBody.h 
    ./qpid/framing/ClusterDeliverToQueueBody.h 
    ./qpid/framing/FileConsumeBody.h 
    ./qpid/framing/SessionCommandPointBody.h 
    ./qpid/framing/ClusterConnectionQueueObserverStateBody.h 
    ../include/qpid/framing/QueueQueryResult.h 
    ./qpid/framing/TxRollbackBody.h 
    ./qpid/framing/ClusterConfigChangeBody.h 
    ./qpid/framing/ConnectionSecureBody.h 
    ./qpid/framing/ConnectionHeartbeatBody.h 
    ../include/qpid/framing/MessageAcquireResult.h 
    ../include/qpid/framing/ExchangeQueryResult.h 
    ./qpid/framing/MessageCancelBody.h 
    ./qpid/framing/SessionExpectedBody.h 
    ../include/qpid/framing/TypeCode.h 
    ./qpid/framing/ClusterConnectionShadowSetUserBody.h 
    ./qpid/framing/ConnectionOpenOkBody.h 
    ./qpid/framing/MessageReleaseBody.h 
    ./qpid/framing/ConnectionOpenBody.h 
    ./qpid/framing/ClusterConnectionTxPublishBody.h 
    ./qpid/framing/ClusterConnectionExchangeBody.h 
    ./qpid/framing/ClusterConnectionConsumerStateBody.h 
    ./qpid/framing/ClusterReadyBody.h 
    ./qpid/framing/ClusterConnectionClockBody.h 
    ./qpid/framing/ClusterConnectionDeliverDoOutputBody.h 
    ./qpid/framing/MessageSubscribeBody.h 
    ./qpid/framing/DtxRollbackBody.h)

set(qpid_client_no_keyworddir  ${includedir}/qpid/client/no_keyword)
set(dist_qpid_client_no_keyword_HEADERS ../include/qpid/client/no_keyword/AsyncSession_0_10.h 
    ../include/qpid/client/no_keyword/Session_0_10.h)

set(qpid_clientdir  ${includedir}/qpid/client)
set(dist_qpid_client_HEADERS ../include/qpid/client/AsyncSession_0_10.h 
    ../include/qpid/client/Session_0_10.h 
    ../include/qpid/client/arg.h)

set(qpid_brokerdir  ${includedir}/qpid/broker)
set(dist_qpid_broker_HEADERS )

