# Generated makefile fragment.
# Including makefile defines $(rgen_dir) $(rgen_cmd) and $(specs).

rgen_generator=$(rgen_dir)/framing.0-10/OperationsInvoker.rb \
    $(rgen_dir)/framing.0-10/MethodBodyConstVisitor.rb \
    $(rgen_dir)/framing.0-10/frame_body_lists.rb \
    $(rgen_dir)/framing.0-10/Proxy.rb \
    $(rgen_dir)/framing.0-10/structs.rb \
    $(rgen_dir)/framing.0-10/constants.rb \
    $(rgen_dir)/framing.0-10/Operations.rb \
    $(rgen_dir)/framing.0-10/all_method_bodies.rb \
    $(rgen_dir)/framing.0-10/MethodBodyFactory.rb \
    $(rgen_dir)/framing.0-10/Session.rb \
    $(rgen_dir)/framing.0-10/MethodBodyDefaultVisitor.rb \
    $(rgen_dir)/amqpgen.rb \
    $(rgen_dir)/0-10/handlers.rb \
    $(rgen_dir)/0-10/typecode.rb \
    $(rgen_dir)/0-10/allsegmenttypes.rb \
    $(rgen_dir)/0-10/exceptions.rb \
    $(rgen_dir)/0-10/specification.rb \
    $(rgen_dir)/cppgen.rb \
    $(rgen_dir)/MethodBodyDefaultVisitor.rb \
    $(rgen_dir)/generate

rgen_amqp_0_10_srcs = ./qpid/amqp_0_10/StructVisitor.h \
    ./qpid/amqp_0_10/specification.cpp \
    ./qpid/amqp_0_10/ControlVisitor.h \
    ./qpid/amqp_0_10/TypeForCode.cpp \
    ./qpid/amqp_0_10/CommandHolder.cpp \
    ./qpid/amqp_0_10/TypeForCode.h \
    ./qpid/amqp_0_10/StructHolder.h \
    ./qpid/amqp_0_10/structs.cpp \
    ./qpid/amqp_0_10/ProxyTemplate.h \
    ./qpid/amqp_0_10/structs.h \
    ./qpid/amqp_0_10/CodeForType.cpp \
    ./qpid/amqp_0_10/CommandVisitor.h \
    ./qpid/amqp_0_10/ApplyStruct.h \
    ./qpid/amqp_0_10/CodeForType.h \
    ./qpid/amqp_0_10/CommandHolder.h \
    ./qpid/amqp_0_10/exceptions.h \
    ./qpid/amqp_0_10/specification_fwd.h \
    ./qpid/amqp_0_10/StructHolder.cpp \
    ./qpid/amqp_0_10/ApplyControl.h \
    ./qpid/amqp_0_10/ControlHolder.cpp \
    ./qpid/amqp_0_10/ControlHolder.h \
    ./qpid/amqp_0_10/ApplyCommand.h \
    ./qpid/amqp_0_10/specification.h \
    ./qpid/amqp_0_10/handlers.h

rgen_framing_srcs = ./qpid/framing/ClusterConnectionClockBody.cpp \
    ./qpid/framing/ClusterConnectionDtxAckBody.cpp \
    ./qpid/framing/ClusterConnectionTxAcceptBody.h \
    ./qpid/framing/MessageTransferBody.h \
    ./qpid/framing/TypeCode.cpp \
    ./qpid/framing/ClusterConnectionExchangeBody.cpp \
    ./qpid/framing/ExchangeBoundBody.cpp \
    ./qpid/framing/MessageAcquireBody.h \
    ./qpid/framing/MessageSubscribeBody.h \
    ./qpid/framing/ConnectionCloseOkBody.cpp \
    ./qpid/framing/ClusterConnectionQueuePositionBody.cpp \
    ./qpid/framing/ClusterConnectionSessionStateBody.cpp \
    ./qpid/framing/SessionFlushBody.h \
    ./qpid/framing/SessionKnownCompletedBody.cpp \
    ./qpid/framing/SessionTimeoutBody.cpp \
    ./qpid/framing/ClusterConnectionTxEndBody.h \
    ./qpid/framing/ClusterConnectionShadowSetUserBody.cpp \
    ./qpid/framing/ConnectionRedirectBody.h \
    ./qpid/framing/TxCommitBody.h \
    ./qpid/framing/ExchangeBoundResult.cpp \
    ./qpid/framing/ClusterDeliverToQueueBody.cpp \
    ./qpid/framing/ClusterTimerWakeupBody.cpp \
    ../include/qpid/framing/DeliveryProperties.h \
    ./qpid/framing/DtxForgetBody.h \
    ./qpid/framing/ClusterRetractOfferBody.h \
    ./qpid/framing/ReplyTo.cpp \
    ./qpid/framing/ClusterUpdateRequestBody.cpp \
    ./qpid/framing/SessionAttachBody.h \
    ./qpid/framing/FileOpenBody.cpp \
    ./qpid/framing/StreamConsumeBody.cpp \
    ./qpid/framing/ConnectionOpenOkBody.cpp \
    ../include/qpid/framing/Header.h \
    ./qpid/framing/ClusterConnectionSessionStateBody.h \
    ./qpid/framing/ClusterConnectionShadowPrepareBody.cpp \
    ../include/qpid/framing/Xid.h \
    ./qpid/framing/SessionRequestTimeoutBody.h \
    ./qpid/framing/ConnectionCloseOkBody.h \
    ./qpid/framing/FileConsumeOkBody.cpp \
    ./qpid/framing/XaResult.cpp \
    ./qpid/framing/DtxStartBody.h \
    ./qpid/framing/ExchangeQueryResult.cpp \
    ./qpid/framing/DtxGetTimeoutBody.h \
    ./qpid/framing/DtxCommitBody.h \
    ./qpid/framing/SessionGapBody.cpp \
    ./qpid/framing/ConnectionStartOkBody.cpp \
    ./qpid/framing/FileStageBody.cpp \
    ./qpid/framing/MessageReleaseBody.cpp \
    ./qpid/framing/MessageAcquireBody.cpp \
    ./qpid/framing/DtxEndBody.cpp \
    ./qpid/framing/FileReturnBody.h \
    ./qpid/framing/FileQosBody.h \
    ./qpid/framing/ClusterConnectionRetractOfferBody.h \
    ./qpid/framing/ClusterReadyBody.h \
    ./qpid/framing/SessionCompletedBody.cpp \
    ./qpid/framing/FileOpenBody.h \
    ./qpid/framing/StreamConsumeOkBody.cpp \
    ./qpid/framing/ExchangeDeleteBody.cpp \
    ./qpid/framing/ClusterConnectionAddQueueListenerBody.h \
    ./qpid/framing/ClusterConnectionAccumulatedAckBody.cpp \
    ./qpid/framing/FileOpenOkBody.h \
    ./qpid/framing/FileRejectBody.cpp \
    ./qpid/framing/ClusterInitialStatusBody.h \
    ./qpid/framing/StreamQosBody.h \
    ./qpid/framing/ExchangeQueryBody.cpp \
    ./qpid/framing/DtxRollbackBody.h \
    ./qpid/framing/StreamDeliverBody.cpp \
    ./qpid/framing/DtxRecoverBody.cpp \
    ./qpid/framing/SessionAttachedBody.cpp \
    ./qpid/framing/MessageProperties.cpp \
    ./qpid/framing/frame_body_lists.h \
    ./qpid/framing/ConnectionOpenOkBody.h \
    ./qpid/framing/ClusterConnectionQueueObserverStateBody.h \
    ./qpid/framing/ClusterConnectionDtxAckBody.h \
    ./qpid/framing/ExchangeDeclareBody.cpp \
    ./qpid/framing/ClusterConnectionAbortBody.h \
    ./qpid/framing/ClusterShutdownBody.h \
    ./qpid/framing/ExchangeDeclareBody.h \
    ./qpid/framing/ExchangeBindBody.cpp \
    ./qpid/framing/MessageAcceptBody.cpp \
    ./qpid/framing/StreamCancelBody.cpp \
    ../include/qpid/framing/ExchangeBoundResult.h \
    ./qpid/framing/reply_exceptions.cpp \
    ./qpid/framing/ClusterConnectionTxAcceptBody.cpp \
    ../include/qpid/framing/ExchangeQueryResult.h \
    ./qpid/framing/MessageFlowBody.cpp \
    ../include/qpid/framing/MessageProperties.h \
    ./qpid/framing/SessionTimeoutBody.h \
    ../include/qpid/framing/DtxGetTimeoutResult.h \
    ./qpid/framing/SessionDetachedBody.cpp \
    ./qpid/framing/ClusterConnectionConfigBody.h \
    ./qpid/framing/ClusterConnectionOutputTaskBody.h \
    ./qpid/framing/ConnectionHeartbeatBody.h \
    ./qpid/framing/FileQosOkBody.cpp \
    ./qpid/framing/ClusterTimerDropBody.h \
    ./qpid/framing/AMQP_AllProxy.h \
    ./qpid/framing/ClusterConnectionShadowReadyBody.h \
    ./qpid/framing/ClusterClockBody.cpp \
    ./qpid/framing/StreamPublishBody.cpp \
    ./qpid/framing/ServerInvoker.h \
    ./qpid/framing/ClusterConnectionDtxEndBody.cpp \
    ./qpid/framing/ClusterConnectionConsumerStateBody.cpp \
    ./qpid/framing/ConnectionCloseBody.cpp \
    ./qpid/framing/AMQP_AllProxy.cpp \
    ./qpid/framing/FileReturnBody.cpp \
    ./qpid/framing/SessionFlushBody.cpp \
    ./qpid/framing/ConnectionStartBody.cpp \
    ../include/qpid/framing/amqp_structs.h \
    ./qpid/framing/ClusterConnectionTxPublishBody.cpp \
    ./qpid/framing/FileQosOkBody.h \
    ./qpid/framing/MessageSubscribeBody.cpp \
    ./qpid/framing/DtxGetTimeoutBody.cpp \
    ./qpid/framing/ConnectionSecureBody.h \
    ./qpid/framing/MessageStopBody.cpp \
    ./qpid/framing/MethodBodyDefaultVisitor.h \
    ./qpid/framing/ClusterTimerWakeupBody.h \
    ./qpid/framing/ClusterReadyBody.cpp \
    ./qpid/framing/ClusterUpdateRequestBody.h \
    ./qpid/framing/DtxRecoverResult.cpp \
    ./qpid/framing/SessionConfirmedBody.h \
    ./qpid/framing/FileCancelBody.h \
    ./qpid/framing/SessionRequestTimeoutBody.cpp \
    ./qpid/framing/DtxSetTimeoutBody.cpp \
    ./qpid/framing/ExecutionExceptionBody.h \
    ./qpid/framing/SessionCommandPointBody.cpp \
    ./qpid/framing/MethodBodyFactory.cpp \
    ./qpid/framing/AMQP_AllOperations.h \
    ./qpid/framing/ClusterConnectionDtxStartBody.h \
    ./qpid/framing/ClusterTimerDropBody.cpp \
    ./qpid/framing/ExchangeDeleteBody.h \
    ./qpid/framing/DtxStartBody.cpp \
    ./qpid/framing/ExecutionExceptionBody.cpp \
    ./qpid/framing/ClusterShutdownBody.cpp \
    ./qpid/framing/ExchangeBindBody.h \
    ./qpid/framing/DtxEndBody.h \
    ./qpid/framing/DtxSetTimeoutBody.h \
    ./qpid/framing/ClusterErrorCheckBody.h \
    ./qpid/framing/SessionConfirmedBody.cpp \
    ./qpid/framing/ClusterInitialStatusBody.cpp \
    ./qpid/framing/FileCancelBody.cpp \
    ./qpid/framing/SessionCompletedBody.h \
    ../include/qpid/framing/DtxRecoverResult.h \
    ./qpid/framing/QueueDeclareBody.cpp \
    ./qpid/framing/all_method_bodies.h \
    ./qpid/framing/Xid.cpp \
    ./qpid/framing/StreamQosOkBody.cpp \
    ./qpid/framing/ClusterRetractOfferBody.cpp \
    ./qpid/framing/ClusterConnectionQueueObserverStateBody.cpp \
    ./qpid/framing/QueueDeleteBody.cpp \
    ./qpid/framing/MessageAcquireResult.cpp \
    ./qpid/framing/MessageRejectBody.h \
    ./qpid/framing/ClusterConnectionQueueDequeueSincePurgeStateBody.h \
    ./qpid/framing/ClusterConnectionShadowSetUserBody.h \
    ./qpid/framing/FilePublishBody.h \
    ./qpid/framing/ClusterUpdateOfferBody.h \
    ./qpid/framing/ClusterConnectionTxEndBody.cpp \
    ./qpid/framing/AMQP_ClientProxy.h \
    ./qpid/framing/MessageTransferBody.cpp \
    ./qpid/framing/QueueQueryBody.h \
    ./qpid/framing/ClusterConnectionTxEnqueueBody.cpp \
    ../include/qpid/framing/MessageAcquireResult.h \
    ./qpid/framing/MethodBodyConstVisitor.h \
    ./qpid/framing/StreamConsumeBody.h \
    ./qpid/framing/FileConsumeBody.h \
    ./qpid/framing/ClusterConnectionInternalStateBody.h \
    ./qpid/framing/ClusterConnectionAddQueueListenerBody.cpp \
    ./qpid/framing/ClusterConnectionTxStartBody.h \
    ./qpid/framing/ClusterConnectionAnnounceBody.h \
    ./qpid/framing/FileOpenOkBody.cpp \
    ./qpid/framing/FileDeliverBody.cpp \
    ./qpid/framing/ClusterConnectionShadowReadyBody.cpp \
    ./qpid/framing/StreamDeliverBody.h \
    ./qpid/framing/ConnectionHeartbeatBody.cpp \
    ./qpid/framing/AMQP_ServerProxy.cpp \
    ./qpid/framing/StreamQosBody.cpp \
    ./qpid/framing/ClusterConnectionClockBody.h \
    ./qpid/framing/ClusterConnectionDtxWorkRecordBody.cpp \
    ./qpid/framing/MessageStopBody.h \
    ./qpid/framing/ExecutionResultBody.h \
    ./qpid/framing/ClusterConnectionTxEnqueueBody.h \
    ./qpid/framing/MessageReleaseBody.h \
    ../include/qpid/framing/FragmentProperties.h \
    ./qpid/framing/ClusterConnectionTxStartBody.cpp \
    ./qpid/framing/SessionAttachBody.cpp \
    ./qpid/framing/ConnectionStartOkBody.h \
    ./qpid/framing/TxRollbackBody.cpp \
    ./qpid/framing/ClusterConnectionQueueFairshareStateBody.cpp \
    ./qpid/framing/ClusterConnectionConsumerStateBody.h \
    ./qpid/framing/ClusterConnectionDeliverCloseBody.h \
    ./qpid/framing/ClusterErrorCheckBody.cpp \
    ../include/qpid/framing/XaResult.h \
    ./qpid/framing/SessionDetachBody.cpp \
    ./qpid/framing/AMQP_ServerProxy.h \
    ./qpid/framing/ConnectionCloseBody.h \
    ./qpid/framing/DtxPrepareBody.cpp \
    ./qpid/framing/ClusterConnectionExchangeBody.h \
    ./qpid/framing/ConnectionStartBody.h \
    ./qpid/framing/FragmentProperties.cpp \
    ./qpid/framing/DtxRecoverBody.h \
    ../include/qpid/framing/TypeCode.h \
    ./qpid/framing/ClusterConnectionQueueDequeueSincePurgeStateBody.cpp \
    ./qpid/framing/ClusterConnectionQueuePositionBody.h \
    ./qpid/framing/ExchangeUnbindBody.cpp \
    ./qpid/framing/MessageSetFlowModeBody.h \
    ./qpid/framing/StreamCancelBody.h \
    ../include/qpid/framing/reply_exceptions.h \
    ./qpid/framing/ClusterConnectionInternalStateBody.cpp \
    ./qpid/framing/ClusterDeliverToQueueBody.h \
    ./qpid/framing/MessageFlushBody.cpp \
    ./qpid/framing/MessageCancelBody.h \
    ./qpid/framing/MessageAcceptBody.h \
    ./qpid/framing/ExecutionSyncBody.cpp \
    ./qpid/framing/ClusterConnectionRetractOfferBody.cpp \
    ./qpid/framing/ClusterConnectionAbortBody.cpp \
    ./qpid/framing/DtxSelectBody.h \
    ../include/qpid/framing/StreamProperties.h \
    ./qpid/framing/FileQosBody.cpp \
    ./qpid/framing/StreamReturnBody.cpp \
    ./qpid/framing/ClusterUpdateOfferBody.cpp \
    ./qpid/framing/ClusterConnectionTxDequeueBody.cpp \
    ./qpid/framing/ClusterConnectionTxDequeueBody.h \
    ./qpid/framing/ClusterConnectionAnnounceBody.cpp \
    ./qpid/framing/ConnectionTuneOkBody.h \
    ./qpid/framing/SessionDetachBody.h \
    ../include/qpid/framing/QueueQueryResult.h \
    ./qpid/framing/TxSelectBody.h \
    ./qpid/framing/MessageFlushBody.h \
    ./qpid/framing/MethodBodyDefaultVisitor.cpp \
    ./qpid/framing/ClusterConnectionOutputTaskBody.cpp \
    ./qpid/framing/ConnectionTuneBody.cpp \
    ./qpid/framing/SessionKnownCompletedBody.h \
    ./qpid/framing/SessionGapBody.h \
    ./qpid/framing/FileAckBody.cpp \
    ./qpid/framing/ClientInvoker.h \
    ./qpid/framing/AllInvoker.cpp \
    ./qpid/framing/ClusterConnectionMembershipBody.cpp \
    ./qpid/framing/ClusterConnectionDtxWorkRecordBody.h \
    ./qpid/framing/ClusterConnectionDtxStartBody.cpp \
    ./qpid/framing/ClusterClockBody.h \
    ./qpid/framing/MessageResumeBody.h \
    ../include/qpid/framing/MessageResumeResult.h \
    ./qpid/framing/DtxPrepareBody.h \
    ./qpid/framing/QueuePurgeBody.h \
    ./qpid/framing/ExchangeUnbindBody.h \
    ./qpid/framing/ConnectionRedirectBody.cpp \
    ./qpid/framing/ConnectionSecureOkBody.h \
    ./qpid/framing/ClusterConnectionConfigBody.cpp \
    ./qpid/framing/FilePublishBody.cpp \
    ./qpid/framing/AMQP_ClientProxy.cpp \
    ./qpid/framing/ConnectionTuneBody.h \
    ../include/qpid/framing/ReplyTo.h \
    ./qpid/framing/ClusterConnectionDeliverCloseBody.cpp \
    ./qpid/framing/ClusterConfigChangeBody.h \
    ./qpid/framing/DtxCommitBody.cpp \
    ./qpid/framing/SessionCommandPointBody.h \
    ./qpid/framing/StreamConsumeOkBody.h \
    ./qpid/framing/FileRejectBody.h \
    ./qpid/framing/SessionExpectedBody.h \
    ./qpid/framing/AMQP_ServerOperations.h \
    ./qpid/framing/ClusterConnectionDeliverDoOutputBody.cpp \
    ./qpid/framing/TxSelectBody.cpp \
    ./qpid/framing/QueueQueryResult.cpp \
    ./qpid/framing/MessageSetFlowModeBody.cpp \
    ./qpid/framing/DeliveryProperties.cpp \
    ./qpid/framing/StreamPublishBody.h \
    ./qpid/framing/QueuePurgeBody.cpp \
    ./qpid/framing/QueueDeleteBody.h \
    ./qpid/framing/FileDeliverBody.h \
    ./qpid/framing/ClusterConnectionDtxBufferRefBody.h \
    ./qpid/framing/ClusterConnectionDeliveryRecordBody.h \
    ./qpid/framing/DtxSelectBody.cpp \
    ./qpid/framing/ExchangeQueryBody.h \
    ./qpid/framing/ClusterConnectionManagementSetupStateBody.h \
    ./qpid/framing/SessionAttachedBody.h \
    ./qpid/framing/ExecutionResultBody.cpp \
    ./qpid/framing/ConnectionOpenBody.h \
    ./qpid/framing/MessageCancelBody.cpp \
    ./qpid/framing/MessageRejectBody.cpp \
    ./qpid/framing/ClusterConfigChangeBody.cpp \
    ./qpid/framing/QueueQueryBody.cpp \
    ./qpid/framing/ConnectionTuneOkBody.cpp \
    ../include/qpid/framing/FileProperties.h \
    ./qpid/framing/ClusterConnectionDtxBufferRefBody.cpp \
    ./qpid/framing/ConnectionOpenBody.cpp \
    ./qpid/framing/MessageResumeBody.cpp \
    ./qpid/framing/SessionExpectedBody.cpp \
    ./qpid/framing/Header.cpp \
    ./qpid/framing/ClusterConnectionAccumulatedAckBody.h \
    ./qpid/framing/ClusterConnectionTxPublishBody.h \
    ./qpid/framing/ClusterConnectionDeliveryRecordBody.cpp \
    ./qpid/framing/ClusterConnectionDeliverDoOutputBody.h \
    ./qpid/framing/QueueDeclareBody.h \
    ./qpid/framing/ExecutionSyncBody.h \
    ./qpid/framing/ServerInvoker.cpp \
    ./qpid/framing/DtxGetTimeoutResult.cpp \
    ./qpid/framing/ExchangeBoundBody.h \
    ./qpid/framing/SessionDetachedBody.h \
    ./qpid/framing/MessageResumeResult.cpp \
    ../include/qpid/framing/enum.h \
    ./qpid/framing/ClusterConnectionQueueFairshareStateBody.h \
    ./qpid/framing/StreamReturnBody.h \
    ./qpid/framing/FileStageBody.h \
    ./qpid/framing/StreamProperties.cpp \
    ./qpid/framing/AllInvoker.h \
    ./qpid/framing/ClientInvoker.cpp \
    ./qpid/framing/TxCommitBody.cpp \
    ./qpid/framing/DtxForgetBody.cpp \
    ./qpid/framing/ClusterConnectionManagementSetupStateBody.cpp \
    ./qpid/framing/ClusterConnectionMembershipBody.h \
    ./qpid/framing/ClusterConnectionDtxEndBody.h \
    ./qpid/framing/ConnectionSecureOkBody.cpp \
    ./qpid/framing/MessageFlowBody.h \
    ../include/qpid/framing/constants.h \
    ./qpid/framing/ClusterConnectionShadowPrepareBody.h \
    ./qpid/framing/FileProperties.cpp \
    ./qpid/framing/FileConsumeOkBody.h \
    ./qpid/framing/TxRollbackBody.h \
    ./qpid/framing/AMQP_ClientOperations.h \
    ./qpid/framing/FileAckBody.h \
    ./qpid/framing/ConnectionSecureBody.cpp \
    ./qpid/framing/DtxRollbackBody.cpp \
    ./qpid/framing/FileConsumeBody.cpp \
    ./qpid/framing/StreamQosOkBody.h

rgen_client_srcs = ./qpid/client/no_keyword/AsyncSession_0_10.cpp \
    ./qpid/client/no_keyword/Session_0_10.cpp \
    ../include/qpid/client/no_keyword/Session_0_10.h \
    ../include/qpid/client/Session_0_10.h \
    ../include/qpid/client/no_keyword/AsyncSession_0_10.h \
    ../include/qpid/client/AsyncSession_0_10.h \
    ../include/qpid/client/arg.h
rgen_srcs=./qpid/framing/ClusterConnectionClockBody.cpp \
    ./qpid/framing/ClusterConnectionDtxAckBody.cpp \
    ./qpid/framing/ClusterConnectionTxAcceptBody.h \
    ./qpid/framing/MessageTransferBody.h \
    ./qpid/amqp_0_10/StructVisitor.h \
    ./qpid/amqp_0_10/specification.cpp \
    ./qpid/framing/TypeCode.cpp \
    ./qpid/framing/ClusterConnectionExchangeBody.cpp \
    ./qpid/framing/ExchangeBoundBody.cpp \
    ./qpid/framing/MessageAcquireBody.h \
    ./qpid/framing/MessageSubscribeBody.h \
    ./qpid/framing/ConnectionCloseOkBody.cpp \
    ./qpid/framing/ClusterConnectionQueuePositionBody.cpp \
    ./qpid/framing/ClusterConnectionSessionStateBody.cpp \
    ./qpid/framing/SessionFlushBody.h \
    ./qpid/framing/SessionKnownCompletedBody.cpp \
    ./qpid/framing/SessionTimeoutBody.cpp \
    ./qpid/framing/ClusterConnectionTxEndBody.h \
    ./qpid/framing/ClusterConnectionShadowSetUserBody.cpp \
    ./qpid/framing/ConnectionRedirectBody.h \
    ./qpid/framing/TxCommitBody.h \
    ./qpid/framing/ExchangeBoundResult.cpp \
    ./qpid/framing/ClusterDeliverToQueueBody.cpp \
    ./qpid/framing/ClusterTimerWakeupBody.cpp \
    ../include/qpid/framing/DeliveryProperties.h \
    ./qpid/framing/DtxForgetBody.h \
    ./qpid/framing/ClusterRetractOfferBody.h \
    ./qpid/framing/ReplyTo.cpp \
    ./qpid/framing/ClusterUpdateRequestBody.cpp \
    ./qpid/framing/SessionAttachBody.h \
    ./qpid/framing/FileOpenBody.cpp \
    ./qpid/framing/StreamConsumeBody.cpp \
    ./qpid/framing/ConnectionOpenOkBody.cpp \
    ../include/qpid/framing/Header.h \
    ./qpid/framing/ClusterConnectionSessionStateBody.h \
    ./qpid/amqp_0_10/ControlVisitor.h \
    ./qpid/client/no_keyword/AsyncSession_0_10.cpp \
    ./qpid/framing/ClusterConnectionShadowPrepareBody.cpp \
    ../include/qpid/framing/Xid.h \
    ./qpid/framing/SessionRequestTimeoutBody.h \
    ./qpid/amqp_0_10/TypeForCode.cpp \
    ./qpid/framing/ConnectionCloseOkBody.h \
    ./qpid/framing/FileConsumeOkBody.cpp \
    ./qpid/framing/XaResult.cpp \
    ./qpid/amqp_0_10/CommandHolder.cpp \
    ./qpid/framing/DtxStartBody.h \
    ./qpid/framing/ExchangeQueryResult.cpp \
    ./qpid/framing/DtxGetTimeoutBody.h \
    ./qpid/framing/DtxCommitBody.h \
    ./qpid/framing/SessionGapBody.cpp \
    ./qpid/framing/ConnectionStartOkBody.cpp \
    ./qpid/framing/FileStageBody.cpp \
    ./qpid/framing/MessageReleaseBody.cpp \
    ./qpid/framing/MessageAcquireBody.cpp \
    ./qpid/framing/DtxEndBody.cpp \
    ./qpid/framing/FileReturnBody.h \
    ./qpid/framing/FileQosBody.h \
    ./qpid/amqp_0_10/TypeForCode.h \
    ./qpid/framing/ClusterConnectionRetractOfferBody.h \
    ./qpid/framing/ClusterReadyBody.h \
    ./qpid/framing/SessionCompletedBody.cpp \
    ./qpid/framing/FileOpenBody.h \
    ./qpid/framing/StreamConsumeOkBody.cpp \
    ./qpid/framing/ExchangeDeleteBody.cpp \
    ./qpid/amqp_0_10/StructHolder.h \
    ./qpid/framing/ClusterConnectionAddQueueListenerBody.h \
    ./qpid/framing/ClusterConnectionAccumulatedAckBody.cpp \
    ./qpid/framing/FileOpenOkBody.h \
    ./qpid/framing/FileRejectBody.cpp \
    ./qpid/framing/ClusterInitialStatusBody.h \
    ./qpid/framing/StreamQosBody.h \
    ./qpid/framing/ExchangeQueryBody.cpp \
    ./qpid/framing/DtxRollbackBody.h \
    ./qpid/framing/StreamDeliverBody.cpp \
    ./qpid/framing/DtxRecoverBody.cpp \
    ./qpid/framing/SessionAttachedBody.cpp \
    ./qpid/framing/MessageProperties.cpp \
    ./qpid/framing/frame_body_lists.h \
    ./qpid/framing/ConnectionOpenOkBody.h \
    ./qpid/client/no_keyword/Session_0_10.cpp \
    ./qpid/framing/ClusterConnectionQueueObserverStateBody.h \
    ./qpid/framing/ClusterConnectionDtxAckBody.h \
    ./qpid/framing/ExchangeDeclareBody.cpp \
    ./qpid/framing/ClusterConnectionAbortBody.h \
    ./qpid/framing/ClusterShutdownBody.h \
    ./qpid/framing/ExchangeDeclareBody.h \
    ./qpid/framing/ExchangeBindBody.cpp \
    ./qpid/amqp_0_10/structs.cpp \
    ./qpid/amqp_0_10/ProxyTemplate.h \
    ./qpid/framing/MessageAcceptBody.cpp \
    ./qpid/framing/StreamCancelBody.cpp \
    ../include/qpid/framing/ExchangeBoundResult.h \
    ./qpid/framing/reply_exceptions.cpp \
    ./qpid/framing/ClusterConnectionTxAcceptBody.cpp \
    ../include/qpid/framing/ExchangeQueryResult.h \
    ./qpid/framing/MessageFlowBody.cpp \
    ../include/qpid/framing/MessageProperties.h \
    ./qpid/framing/SessionTimeoutBody.h \
    ../include/qpid/framing/DtxGetTimeoutResult.h \
    ./qpid/framing/SessionDetachedBody.cpp \
    ./qpid/framing/ClusterConnectionConfigBody.h \
    ./qpid/framing/ClusterConnectionOutputTaskBody.h \
    ./qpid/framing/ConnectionHeartbeatBody.h \
    ./qpid/framing/FileQosOkBody.cpp \
    ./qpid/amqp_0_10/structs.h \
    ./qpid/framing/ClusterTimerDropBody.h \
    ./qpid/framing/AMQP_AllProxy.h \
    ./qpid/framing/ClusterConnectionShadowReadyBody.h \
    ./qpid/framing/ClusterClockBody.cpp \
    ./qpid/framing/StreamPublishBody.cpp \
    ./qpid/framing/ServerInvoker.h \
    ./qpid/framing/ClusterConnectionDtxEndBody.cpp \
    ./qpid/framing/ClusterConnectionConsumerStateBody.cpp \
    ./qpid/framing/ConnectionCloseBody.cpp \
    ./qpid/framing/AMQP_AllProxy.cpp \
    ./qpid/framing/FileReturnBody.cpp \
    ./qpid/framing/SessionFlushBody.cpp \
    ./qpid/framing/ConnectionStartBody.cpp \
    ../include/qpid/framing/amqp_structs.h \
    ./qpid/framing/ClusterConnectionTxPublishBody.cpp \
    ./qpid/framing/FileQosOkBody.h \
    ./qpid/framing/MessageSubscribeBody.cpp \
    ./qpid/framing/DtxGetTimeoutBody.cpp \
    ./qpid/framing/ConnectionSecureBody.h \
    ./qpid/framing/MessageStopBody.cpp \
    ./qpid/framing/MethodBodyDefaultVisitor.h \
    ./qpid/framing/ClusterTimerWakeupBody.h \
    ./qpid/framing/ClusterReadyBody.cpp \
    ./qpid/framing/ClusterUpdateRequestBody.h \
    ./qpid/framing/DtxRecoverResult.cpp \
    ./qpid/framing/SessionConfirmedBody.h \
    ./qpid/framing/FileCancelBody.h \
    ./qpid/framing/SessionRequestTimeoutBody.cpp \
    ./qpid/framing/DtxSetTimeoutBody.cpp \
    ./qpid/framing/ExecutionExceptionBody.h \
    ./qpid/framing/SessionCommandPointBody.cpp \
    ./qpid/amqp_0_10/CodeForType.cpp \
    ./qpid/framing/MethodBodyFactory.cpp \
    ./qpid/framing/AMQP_AllOperations.h \
    ./qpid/framing/ClusterConnectionDtxStartBody.h \
    ./qpid/framing/ClusterTimerDropBody.cpp \
    ./qpid/framing/ExchangeDeleteBody.h \
    ./qpid/framing/DtxStartBody.cpp \
    ./qpid/framing/ExecutionExceptionBody.cpp \
    ./qpid/framing/ClusterShutdownBody.cpp \
    ./qpid/framing/ExchangeBindBody.h \
    ./qpid/framing/DtxEndBody.h \
    ./qpid/framing/DtxSetTimeoutBody.h \
    ./qpid/amqp_0_10/CommandVisitor.h \
    ./qpid/framing/ClusterErrorCheckBody.h \
    ./qpid/framing/SessionConfirmedBody.cpp \
    ./qpid/framing/ClusterInitialStatusBody.cpp \
    ./qpid/framing/FileCancelBody.cpp \
    ./qpid/framing/SessionCompletedBody.h \
    ../include/qpid/framing/DtxRecoverResult.h \
    ./qpid/framing/QueueDeclareBody.cpp \
    ./qpid/framing/all_method_bodies.h \
    ./qpid/framing/Xid.cpp \
    ./qpid/framing/StreamQosOkBody.cpp \
    ./qpid/framing/ClusterRetractOfferBody.cpp \
    ./qpid/framing/ClusterConnectionQueueObserverStateBody.cpp \
    ./qpid/framing/QueueDeleteBody.cpp \
    ./qpid/framing/MessageAcquireResult.cpp \
    ./qpid/framing/MessageRejectBody.h \
    ./qpid/framing/ClusterConnectionQueueDequeueSincePurgeStateBody.h \
    ./qpid/framing/ClusterConnectionShadowSetUserBody.h \
    ./qpid/framing/FilePublishBody.h \
    ./qpid/framing/ClusterUpdateOfferBody.h \
    ./qpid/framing/ClusterConnectionTxEndBody.cpp \
    ./qpid/framing/AMQP_ClientProxy.h \
    ./qpid/framing/MessageTransferBody.cpp \
    ./qpid/framing/QueueQueryBody.h \
    ./qpid/amqp_0_10/ApplyStruct.h \
    ./qpid/amqp_0_10/CodeForType.h \
    ./qpid/framing/ClusterConnectionTxEnqueueBody.cpp \
    ../include/qpid/framing/MessageAcquireResult.h \
    ./qpid/framing/MethodBodyConstVisitor.h \
    ./qpid/framing/StreamConsumeBody.h \
    ./qpid/framing/FileConsumeBody.h \
    ./qpid/framing/ClusterConnectionInternalStateBody.h \
    ./qpid/framing/ClusterConnectionAddQueueListenerBody.cpp \
    ./qpid/framing/ClusterConnectionTxStartBody.h \
    ./qpid/framing/ClusterConnectionAnnounceBody.h \
    ./qpid/framing/FileOpenOkBody.cpp \
    ./qpid/framing/FileDeliverBody.cpp \
    ./qpid/framing/ClusterConnectionShadowReadyBody.cpp \
    ./qpid/framing/StreamDeliverBody.h \
    ./qpid/framing/ConnectionHeartbeatBody.cpp \
    ./qpid/framing/AMQP_ServerProxy.cpp \
    ./qpid/framing/StreamQosBody.cpp \
    ./qpid/framing/ClusterConnectionClockBody.h \
    ./qpid/framing/ClusterConnectionDtxWorkRecordBody.cpp \
    ./qpid/framing/MessageStopBody.h \
    ./qpid/framing/ExecutionResultBody.h \
    ./qpid/framing/ClusterConnectionTxEnqueueBody.h \
    ./qpid/framing/MessageReleaseBody.h \
    ../include/qpid/framing/FragmentProperties.h \
    ./qpid/framing/ClusterConnectionTxStartBody.cpp \
    ./qpid/framing/SessionAttachBody.cpp \
    ./qpid/framing/ConnectionStartOkBody.h \
    ./qpid/framing/TxRollbackBody.cpp \
    ./qpid/framing/ClusterConnectionQueueFairshareStateBody.cpp \
    ./qpid/framing/ClusterConnectionConsumerStateBody.h \
    ./qpid/framing/ClusterConnectionDeliverCloseBody.h \
    ./qpid/framing/ClusterErrorCheckBody.cpp \
    ../include/qpid/framing/XaResult.h \
    ./qpid/framing/SessionDetachBody.cpp \
    ./qpid/framing/AMQP_ServerProxy.h \
    ./qpid/framing/ConnectionCloseBody.h \
    ./qpid/framing/DtxPrepareBody.cpp \
    ../include/qpid/client/no_keyword/Session_0_10.h \
    ./qpid/framing/ClusterConnectionExchangeBody.h \
    ./qpid/framing/ConnectionStartBody.h \
    ./qpid/framing/FragmentProperties.cpp \
    ./qpid/framing/DtxRecoverBody.h \
    ./qpid/amqp_0_10/CommandHolder.h \
    ./qpid/amqp_0_10/exceptions.h \
    ../include/qpid/framing/TypeCode.h \
    ./qpid/framing/ClusterConnectionQueueDequeueSincePurgeStateBody.cpp \
    ./qpid/framing/ClusterConnectionQueuePositionBody.h \
    ./qpid/framing/ExchangeUnbindBody.cpp \
    ./qpid/framing/MessageSetFlowModeBody.h \
    ./qpid/framing/StreamCancelBody.h \
    ../include/qpid/framing/reply_exceptions.h \
    ./qpid/framing/ClusterConnectionInternalStateBody.cpp \
    ./qpid/framing/ClusterDeliverToQueueBody.h \
    ./qpid/framing/MessageFlushBody.cpp \
    ./qpid/framing/MessageCancelBody.h \
    ./qpid/framing/MessageAcceptBody.h \
    ./qpid/framing/ExecutionSyncBody.cpp \
    ./qpid/framing/ClusterConnectionRetractOfferBody.cpp \
    ./qpid/framing/ClusterConnectionAbortBody.cpp \
    ./qpid/framing/DtxSelectBody.h \
    ../include/qpid/framing/StreamProperties.h \
    ./qpid/framing/FileQosBody.cpp \
    ./qpid/framing/StreamReturnBody.cpp \
    ./qpid/framing/ClusterUpdateOfferBody.cpp \
    ./qpid/framing/ClusterConnectionTxDequeueBody.cpp \
    ./qpid/framing/ClusterConnectionTxDequeueBody.h \
    ./qpid/framing/ClusterConnectionAnnounceBody.cpp \
    ./qpid/framing/ConnectionTuneOkBody.h \
    ./qpid/framing/SessionDetachBody.h \
    ../include/qpid/framing/QueueQueryResult.h \
    ./qpid/framing/TxSelectBody.h \
    ./qpid/framing/MessageFlushBody.h \
    ./qpid/framing/MethodBodyDefaultVisitor.cpp \
    ./qpid/framing/ClusterConnectionOutputTaskBody.cpp \
    ./qpid/framing/ConnectionTuneBody.cpp \
    ./qpid/framing/SessionKnownCompletedBody.h \
    ./qpid/framing/SessionGapBody.h \
    ./qpid/framing/FileAckBody.cpp \
    ./qpid/framing/ClientInvoker.h \
    ./qpid/framing/AllInvoker.cpp \
    ./qpid/framing/ClusterConnectionMembershipBody.cpp \
    ./qpid/framing/ClusterConnectionDtxWorkRecordBody.h \
    ./qpid/framing/ClusterConnectionDtxStartBody.cpp \
    ./qpid/framing/ClusterClockBody.h \
    ./qpid/framing/MessageResumeBody.h \
    ../include/qpid/framing/MessageResumeResult.h \
    ./qpid/framing/DtxPrepareBody.h \
    ./qpid/framing/QueuePurgeBody.h \
    ./qpid/amqp_0_10/specification_fwd.h \
    ./qpid/framing/ExchangeUnbindBody.h \
    ./qpid/framing/ConnectionRedirectBody.cpp \
    ./qpid/framing/ConnectionSecureOkBody.h \
    ./tests/allSegmentTypes.h \
    ../include/qpid/client/Session_0_10.h \
    ./qpid/framing/ClusterConnectionConfigBody.cpp \
    ./qpid/framing/FilePublishBody.cpp \
    ./qpid/framing/AMQP_ClientProxy.cpp \
    ./qpid/framing/ConnectionTuneBody.h \
    ../include/qpid/framing/ReplyTo.h \
    ./qpid/amqp_0_10/StructHolder.cpp \
    ./qpid/framing/ClusterConnectionDeliverCloseBody.cpp \
    ./qpid/framing/ClusterConfigChangeBody.h \
    ./qpid/framing/DtxCommitBody.cpp \
    ./qpid/framing/SessionCommandPointBody.h \
    ./qpid/framing/StreamConsumeOkBody.h \
    ./qpid/framing/FileRejectBody.h \
    ./qpid/framing/SessionExpectedBody.h \
    ./qpid/amqp_0_10/ApplyControl.h \
    ../include/qpid/client/no_keyword/AsyncSession_0_10.h \
    ./qpid/framing/AMQP_ServerOperations.h \
    ./qpid/framing/ClusterConnectionDeliverDoOutputBody.cpp \
    ./qpid/framing/TxSelectBody.cpp \
    ./qpid/framing/QueueQueryResult.cpp \
    ./qpid/framing/MessageSetFlowModeBody.cpp \
    ./qpid/framing/DeliveryProperties.cpp \
    ./qpid/framing/StreamPublishBody.h \
    ./qpid/amqp_0_10/ControlHolder.cpp \
    ../include/qpid/client/AsyncSession_0_10.h \
    ./qpid/framing/QueuePurgeBody.cpp \
    ./qpid/framing/QueueDeleteBody.h \
    ./qpid/framing/FileDeliverBody.h \
    ./qpid/framing/ClusterConnectionDtxBufferRefBody.h \
    ./qpid/framing/ClusterConnectionDeliveryRecordBody.h \
    ./qpid/framing/DtxSelectBody.cpp \
    ./qpid/framing/ExchangeQueryBody.h \
    ./qpid/amqp_0_10/ControlHolder.h \
    ./qpid/framing/ClusterConnectionManagementSetupStateBody.h \
    ./qpid/framing/SessionAttachedBody.h \
    ./qpid/framing/ExecutionResultBody.cpp \
    ./qpid/framing/ConnectionOpenBody.h \
    ./qpid/framing/MessageCancelBody.cpp \
    ./qpid/framing/MessageRejectBody.cpp \
    ./qpid/framing/ClusterConfigChangeBody.cpp \
    ./qpid/framing/QueueQueryBody.cpp \
    ./qpid/framing/ConnectionTuneOkBody.cpp \
    ../include/qpid/framing/FileProperties.h \
    ./qpid/framing/ClusterConnectionDtxBufferRefBody.cpp \
    ./qpid/framing/ConnectionOpenBody.cpp \
    ./qpid/framing/MessageResumeBody.cpp \
    ./qpid/framing/SessionExpectedBody.cpp \
    ./qpid/framing/Header.cpp \
    ../include/qpid/client/arg.h \
    ./qpid/framing/ClusterConnectionAccumulatedAckBody.h \
    ./qpid/framing/ClusterConnectionTxPublishBody.h \
    ./qpid/framing/ClusterConnectionDeliveryRecordBody.cpp \
    ./qpid/framing/ClusterConnectionDeliverDoOutputBody.h \
    ./qpid/framing/QueueDeclareBody.h \
    ./qpid/framing/ExecutionSyncBody.h \
    ./qpid/framing/ServerInvoker.cpp \
    ./qpid/framing/DtxGetTimeoutResult.cpp \
    ./qpid/framing/ExchangeBoundBody.h \
    ./qpid/framing/SessionDetachedBody.h \
    ./qpid/framing/MessageResumeResult.cpp \
    ./qpid/amqp_0_10/ApplyCommand.h \
    ../include/qpid/framing/enum.h \
    ./qpid/framing/ClusterConnectionQueueFairshareStateBody.h \
    ./qpid/framing/StreamReturnBody.h \
    ./qpid/framing/FileStageBody.h \
    ./qpid/framing/StreamProperties.cpp \
    ./qpid/framing/AllInvoker.h \
    ./qpid/framing/ClientInvoker.cpp \
    ./qpid/framing/TxCommitBody.cpp \
    ./qpid/framing/DtxForgetBody.cpp \
    ./qpid/framing/ClusterConnectionManagementSetupStateBody.cpp \
    ./qpid/framing/ClusterConnectionMembershipBody.h \
    ./qpid/framing/ClusterConnectionDtxEndBody.h \
    ./qpid/framing/ConnectionSecureOkBody.cpp \
    ./qpid/framing/MessageFlowBody.h \
    ./qpid/amqp_0_10/specification.h \
    ../include/qpid/framing/constants.h \
    ./qpid/framing/ClusterConnectionShadowPrepareBody.h \
    ./qpid/framing/FileProperties.cpp \
    ./qpid/framing/FileConsumeOkBody.h \
    ./qpid/framing/TxRollbackBody.h \
    ./qpid/amqp_0_10/handlers.h \
    ./qpid/framing/AMQP_ClientOperations.h \
    ./qpid/framing/FileAckBody.h \
    ./qpid/framing/ConnectionSecureBody.cpp \
    ./qpid/framing/DtxRollbackBody.cpp \
    ./qpid/framing/FileConsumeBody.cpp \
    ./qpid/framing/StreamQosOkBody.h

# Header file install rules.
qpid_amqp_0_10dir = $(includedir)/qpid/amqp_0_10
dist_qpid_amqp_0_10_HEADERS = ./qpid/amqp_0_10/StructVisitor.h \
    ./qpid/amqp_0_10/ControlVisitor.h \
    ./qpid/amqp_0_10/TypeForCode.h \
    ./qpid/amqp_0_10/StructHolder.h \
    ./qpid/amqp_0_10/ProxyTemplate.h \
    ./qpid/amqp_0_10/structs.h \
    ./qpid/amqp_0_10/CommandVisitor.h \
    ./qpid/amqp_0_10/ApplyStruct.h \
    ./qpid/amqp_0_10/CodeForType.h \
    ./qpid/amqp_0_10/CommandHolder.h \
    ./qpid/amqp_0_10/exceptions.h \
    ./qpid/amqp_0_10/specification_fwd.h \
    ./qpid/amqp_0_10/ApplyControl.h \
    ./qpid/amqp_0_10/ControlHolder.h \
    ./qpid/amqp_0_10/ApplyCommand.h \
    ./qpid/amqp_0_10/specification.h \
    ./qpid/amqp_0_10/handlers.h

qpid_framingdir = $(includedir)/qpid/framing
dist_qpid_framing_HEADERS = ./qpid/framing/ClusterConnectionTxAcceptBody.h \
    ./qpid/framing/MessageTransferBody.h \
    ./qpid/framing/MessageAcquireBody.h \
    ./qpid/framing/MessageSubscribeBody.h \
    ./qpid/framing/SessionFlushBody.h \
    ./qpid/framing/ClusterConnectionTxEndBody.h \
    ./qpid/framing/ConnectionRedirectBody.h \
    ./qpid/framing/TxCommitBody.h \
    ../include/qpid/framing/DeliveryProperties.h \
    ./qpid/framing/DtxForgetBody.h \
    ./qpid/framing/ClusterRetractOfferBody.h \
    ./qpid/framing/SessionAttachBody.h \
    ../include/qpid/framing/Header.h \
    ./qpid/framing/ClusterConnectionSessionStateBody.h \
    ../include/qpid/framing/Xid.h \
    ./qpid/framing/SessionRequestTimeoutBody.h \
    ./qpid/framing/ConnectionCloseOkBody.h \
    ./qpid/framing/DtxStartBody.h \
    ./qpid/framing/DtxGetTimeoutBody.h \
    ./qpid/framing/DtxCommitBody.h \
    ./qpid/framing/FileReturnBody.h \
    ./qpid/framing/FileQosBody.h \
    ./qpid/framing/ClusterConnectionRetractOfferBody.h \
    ./qpid/framing/ClusterReadyBody.h \
    ./qpid/framing/FileOpenBody.h \
    ./qpid/framing/ClusterConnectionAddQueueListenerBody.h \
    ./qpid/framing/FileOpenOkBody.h \
    ./qpid/framing/ClusterInitialStatusBody.h \
    ./qpid/framing/StreamQosBody.h \
    ./qpid/framing/DtxRollbackBody.h \
    ./qpid/framing/frame_body_lists.h \
    ./qpid/framing/ConnectionOpenOkBody.h \
    ./qpid/framing/ClusterConnectionQueueObserverStateBody.h \
    ./qpid/framing/ClusterConnectionDtxAckBody.h \
    ./qpid/framing/ClusterConnectionAbortBody.h \
    ./qpid/framing/ClusterShutdownBody.h \
    ./qpid/framing/ExchangeDeclareBody.h \
    ../include/qpid/framing/ExchangeBoundResult.h \
    ../include/qpid/framing/ExchangeQueryResult.h \
    ../include/qpid/framing/MessageProperties.h \
    ./qpid/framing/SessionTimeoutBody.h \
    ../include/qpid/framing/DtxGetTimeoutResult.h \
    ./qpid/framing/ClusterConnectionConfigBody.h \
    ./qpid/framing/ClusterConnectionOutputTaskBody.h \
    ./qpid/framing/ConnectionHeartbeatBody.h \
    ./qpid/framing/ClusterTimerDropBody.h \
    ./qpid/framing/AMQP_AllProxy.h \
    ./qpid/framing/ClusterConnectionShadowReadyBody.h \
    ./qpid/framing/ServerInvoker.h \
    ../include/qpid/framing/amqp_structs.h \
    ./qpid/framing/FileQosOkBody.h \
    ./qpid/framing/ConnectionSecureBody.h \
    ./qpid/framing/MethodBodyDefaultVisitor.h \
    ./qpid/framing/ClusterTimerWakeupBody.h \
    ./qpid/framing/ClusterUpdateRequestBody.h \
    ./qpid/framing/SessionConfirmedBody.h \
    ./qpid/framing/FileCancelBody.h \
    ./qpid/framing/ExecutionExceptionBody.h \
    ./qpid/framing/AMQP_AllOperations.h \
    ./qpid/framing/ClusterConnectionDtxStartBody.h \
    ./qpid/framing/ExchangeDeleteBody.h \
    ./qpid/framing/ExchangeBindBody.h \
    ./qpid/framing/DtxEndBody.h \
    ./qpid/framing/DtxSetTimeoutBody.h \
    ./qpid/framing/ClusterErrorCheckBody.h \
    ./qpid/framing/SessionCompletedBody.h \
    ../include/qpid/framing/DtxRecoverResult.h \
    ./qpid/framing/all_method_bodies.h \
    ./qpid/framing/MessageRejectBody.h \
    ./qpid/framing/ClusterConnectionQueueDequeueSincePurgeStateBody.h \
    ./qpid/framing/ClusterConnectionShadowSetUserBody.h \
    ./qpid/framing/FilePublishBody.h \
    ./qpid/framing/ClusterUpdateOfferBody.h \
    ./qpid/framing/AMQP_ClientProxy.h \
    ./qpid/framing/QueueQueryBody.h \
    ../include/qpid/framing/MessageAcquireResult.h \
    ./qpid/framing/MethodBodyConstVisitor.h \
    ./qpid/framing/StreamConsumeBody.h \
    ./qpid/framing/FileConsumeBody.h \
    ./qpid/framing/ClusterConnectionInternalStateBody.h \
    ./qpid/framing/ClusterConnectionTxStartBody.h \
    ./qpid/framing/ClusterConnectionAnnounceBody.h \
    ./qpid/framing/StreamDeliverBody.h \
    ./qpid/framing/ClusterConnectionClockBody.h \
    ./qpid/framing/MessageStopBody.h \
    ./qpid/framing/ExecutionResultBody.h \
    ./qpid/framing/ClusterConnectionTxEnqueueBody.h \
    ./qpid/framing/MessageReleaseBody.h \
    ../include/qpid/framing/FragmentProperties.h \
    ./qpid/framing/ConnectionStartOkBody.h \
    ./qpid/framing/ClusterConnectionConsumerStateBody.h \
    ./qpid/framing/ClusterConnectionDeliverCloseBody.h \
    ../include/qpid/framing/XaResult.h \
    ./qpid/framing/AMQP_ServerProxy.h \
    ./qpid/framing/ConnectionCloseBody.h \
    ./qpid/framing/ClusterConnectionExchangeBody.h \
    ./qpid/framing/ConnectionStartBody.h \
    ./qpid/framing/DtxRecoverBody.h \
    ../include/qpid/framing/TypeCode.h \
    ./qpid/framing/ClusterConnectionQueuePositionBody.h \
    ./qpid/framing/MessageSetFlowModeBody.h \
    ./qpid/framing/StreamCancelBody.h \
    ../include/qpid/framing/reply_exceptions.h \
    ./qpid/framing/ClusterDeliverToQueueBody.h \
    ./qpid/framing/MessageCancelBody.h \
    ./qpid/framing/MessageAcceptBody.h \
    ./qpid/framing/DtxSelectBody.h \
    ../include/qpid/framing/StreamProperties.h \
    ./qpid/framing/ClusterConnectionTxDequeueBody.h \
    ./qpid/framing/ConnectionTuneOkBody.h \
    ./qpid/framing/SessionDetachBody.h \
    ../include/qpid/framing/QueueQueryResult.h \
    ./qpid/framing/TxSelectBody.h \
    ./qpid/framing/MessageFlushBody.h \
    ./qpid/framing/SessionKnownCompletedBody.h \
    ./qpid/framing/SessionGapBody.h \
    ./qpid/framing/ClientInvoker.h \
    ./qpid/framing/ClusterConnectionDtxWorkRecordBody.h \
    ./qpid/framing/ClusterClockBody.h \
    ./qpid/framing/MessageResumeBody.h \
    ../include/qpid/framing/MessageResumeResult.h \
    ./qpid/framing/DtxPrepareBody.h \
    ./qpid/framing/QueuePurgeBody.h \
    ./qpid/framing/ExchangeUnbindBody.h \
    ./qpid/framing/ConnectionSecureOkBody.h \
    ./qpid/framing/ConnectionTuneBody.h \
    ../include/qpid/framing/ReplyTo.h \
    ./qpid/framing/ClusterConfigChangeBody.h \
    ./qpid/framing/SessionCommandPointBody.h \
    ./qpid/framing/StreamConsumeOkBody.h \
    ./qpid/framing/FileRejectBody.h \
    ./qpid/framing/SessionExpectedBody.h \
    ./qpid/framing/AMQP_ServerOperations.h \
    ./qpid/framing/StreamPublishBody.h \
    ./qpid/framing/QueueDeleteBody.h \
    ./qpid/framing/FileDeliverBody.h \
    ./qpid/framing/ClusterConnectionDtxBufferRefBody.h \
    ./qpid/framing/ClusterConnectionDeliveryRecordBody.h \
    ./qpid/framing/ExchangeQueryBody.h \
    ./qpid/framing/ClusterConnectionManagementSetupStateBody.h \
    ./qpid/framing/SessionAttachedBody.h \
    ./qpid/framing/ConnectionOpenBody.h \
    ../include/qpid/framing/FileProperties.h \
    ./qpid/framing/ClusterConnectionAccumulatedAckBody.h \
    ./qpid/framing/ClusterConnectionTxPublishBody.h \
    ./qpid/framing/ClusterConnectionDeliverDoOutputBody.h \
    ./qpid/framing/QueueDeclareBody.h \
    ./qpid/framing/ExecutionSyncBody.h \
    ./qpid/framing/ExchangeBoundBody.h \
    ./qpid/framing/SessionDetachedBody.h \
    ../include/qpid/framing/enum.h \
    ./qpid/framing/ClusterConnectionQueueFairshareStateBody.h \
    ./qpid/framing/StreamReturnBody.h \
    ./qpid/framing/FileStageBody.h \
    ./qpid/framing/AllInvoker.h \
    ./qpid/framing/ClusterConnectionMembershipBody.h \
    ./qpid/framing/ClusterConnectionDtxEndBody.h \
    ./qpid/framing/MessageFlowBody.h \
    ../include/qpid/framing/constants.h \
    ./qpid/framing/ClusterConnectionShadowPrepareBody.h \
    ./qpid/framing/FileConsumeOkBody.h \
    ./qpid/framing/TxRollbackBody.h \
    ./qpid/framing/AMQP_ClientOperations.h \
    ./qpid/framing/FileAckBody.h \
    ./qpid/framing/StreamQosOkBody.h

qpid_client_no_keyworddir = $(includedir)/qpid/client/no_keyword
dist_qpid_client_no_keyword_HEADERS = ../include/qpid/client/no_keyword/Session_0_10.h \
    ../include/qpid/client/no_keyword/AsyncSession_0_10.h

qpid_clientdir = $(includedir)/qpid/client
dist_qpid_client_HEADERS = ../include/qpid/client/Session_0_10.h \
    ../include/qpid/client/AsyncSession_0_10.h \
    ../include/qpid/client/arg.h

qpid_brokerdir = $(includedir)/qpid/broker
dist_qpid_broker_HEADERS = 

